### ISSUE TITLE
Deep Learning for Identifying Metastatic Breast Cancer

### ISSUE THREAD

**Issue by evancofer** [greenelab/deep-review#102]
https://arxiv.org/abs/1606.05718
#### Abstract

> The International Symposium on Biomedical Imaging (ISBI) held a grand challenge to evaluate computational systems for the automated detection of metastatic breast cancer in whole slide images of sentinel lymph node biopsies. Our team won both competitions in the grand challenge, obtaining an area under the receiver operating curve (AUC) of 0.925 for the task of whole slide image classification and a score of 0.7051 for the tumor localization task. A pathologist independently reviewed the same images, obtaining a whole slide image classification AUC of 0.966 and a tumor localization score of 0.733. Combining our deep learning system's predictions with the human pathologist's diagnoses increased the pathologist's AUC to 0.995, representing an approximately 85 percent reduction in human error rate. These results demonstrate the power of using deep learning to produce significant improvements in the accuracy of pathological diagnoses.

**Comment by cgreene** [comment]
Won ISBI challenge. Can be combined with human pathologist for improved performance.

Examines whole slide images for cancer mets in lymph nodes. Constructs a probability map for each slide.The AUC of the method alone is 0.9250. It's particularly good at low false positive rates. A human pathologist got an AUC of 0.9664 (with no false positives). The authors claim that combining the predictions of their system with the pathologist provided an AUC of 0.9948. How these were combined is a bit of a mystery to me at this point. Later they state that:
> Importantly, the errors made by our deep learning system were not strongly correlated with the errors made by a human pathologist

Probably the assumption is some sort of post-hoc combination strategy. I think that this is worth talking about, particularly in the context of all the mammography results.

**Comment by cgreene** [comment]
Discussed in #167
