### ISSUE TITLE
feature and labels 

### ISSUE THREAD

**Issue by Mohamed-ElhajAbdou** [greenelab/deep-review#1026]
Hello, i have questions hope i get the answers from you 

1- first the rule of the sequence alignment is that to extract a chunks of subsequences represents the first sequence 

2- and then those alignments are fed to the covariance matrix to extract a matrix called covariance matrix the measures the correlations between each of these alignments with each other

3-from what i understand it that proteins contact map describe the distance matrix as a label , like for example the distance between the first amino acid in the first chain and the first amino acid in the second chain is equal to 200 A, we set a threshold with 8 A so the proteins contact map description for this distance number will be "not in contact" "False" or in binary world "0"  is im right with that understanding

My Questions 
First
1-what is the rule of the covariance matrix
2- what is the rule of proteins contact map are those the labels of the matrix distances if so what is the rule of the covariance matrix 
3- what is the input to the neural network model 
	A- what is the feature, are those the distance matrix if yes what is the rule of covariance matrix
	B- what is the label of these features  are Proteins contact map is the labels in (0's and 1's )

thanks in advance

**Comment by agitter** [comment]
Hi @Mohamed-ElhajAbdou this GitHub repository is being used to write a review manuscript about deep learning literature.  Most of the contributors do not work directly on the specific type of research problem you describe.  You may be able to get your questions answered by checking some of the manuscripts we discuss in [the relevant section of the review](https://greenelab.github.io/deep-review/#protein-secondary-and-tertiary-structure) and contacting their authors.

There also some newer papers being discussed in #1003 that may help you find appropriate researchers to contact.

I'm closing this so we can keep the discussion in this repository focused on the review manuscript.
