### ISSUE TITLE
Why Patient Matching Is a Challenge: Research on Master Patient Index (MPI) Data Discrepancies in Key Identifying Fields.

### ISSUE THREAD

**Issue by cgreene** [greenelab/deep-review#107]
It can be hard to even match the primary index of the EHR - a patient. This study of ~400k duplicates looked at the reasons (note - duplicates were determined through some relatively simple rules and hand evaluated - no deep learning here):
https://www.ncbi.nlm.nih.gov/pubmed/27134610

Some interesting observations - 50% of SSN discrepancies arose from default values. Typographical issues are also a frequent cause with SSNs and names.

**Comment by cgreene** [comment]
@XieConnect : I have this one in - for now - as one of the challenges facing deep methods in this domain (something like: when ground truth isn't). But it's not in as an example of a deep method.

**Comment by agapow** [comment]
This might be usefully pushed into the data standards & integration section.

**Comment by cgreene** [comment]
I think it's touched on here:
https://github.com/greenelab/deep-review/blame/master/sections/03_categorize.md#L315
