### ISSUE TITLE
DeepBind: Predicting the sequence specificities of DNA- and RNA-binding proteins by deep learning

### ISSUE THREAD

**Issue by cgreene** [greenelab/deep-review#11]
https://dx.doi.org/10.1038/nbt.3300

**Comment by agitter** [comment]
This study of Mendelian erythroid disorders could be a good way to show how systems like DeepBind can be used to study disease: http://doi.org/10.1073/pnas.1521754113

GATA1 binding is known to be affected by non-coding variants in some of these diseases.  Most of the study focuses on using CRISPR/Cas9 to perturb GATA1 binding and showing how that affects the expression of a few causal genes for different diseases.  However, they also use pretrained DeepBind (and gkmer-SVM) to study how GATA1 (and related TF) binding may affect additional Mendelian erythroid disorder genes.
