### ISSUE TITLE
Machine learning applications in genetics and genomics

### ISSUE THREAD

**Issue by agitter** [greenelab/deep-review#131]
http://doi.org/10.1038/nrg3920

> The field of machine learning, which aims to develop computer algorithms that improve with experience, holds promise to enable computers to assist humans in the analysis of large, complex data sets. Here, we provide an overview of machine learning applications for the analysis of genome sequencing data sets, including the annotation of sequence elements and epigenetic, proteomic or metabolomic data. We present considerations and recurrent challenges in the application of supervised, semi-supervised and unsupervised machine learning methods, as well as of generative and discriminative modelling approaches. We provide general guidelines to assist in the selection of these machine learning methods and their practical application for the analysis of genetic and genomic data sets.

This review is not about deep learning but can be used to introduce machine learning concepts that we do not want to cover in depth ourselves.

**Comment by XieConnect** [comment]
Agreed. May wait and see how much we want to refer to this work. 
If needed later, I can provide a brief summary (what problems covered, what ML models, what challenges). I read this work some time ago.

**Comment by agitter** [comment]
Yes, I agree that we don't need a summary now.

**Comment by cgreene** [comment]
This has been cited in #540.
