### ISSUE TITLE
Bidirectional LSTM-CRF for Clinical Concept Extraction

### ISSUE THREAD

**Issue by agitter** [greenelab/deep-review#150]
https://arxiv.org/abs/1611.08373

> Automated extraction of concepts from patient clinical records is an essential facilitator of clinical research. For this reason, the 2010 i2b2/VA Natural Language Processing Challenges for Clinical Records introduced a concept extraction task aimed at identifying and classifying concepts into predefined categories (i.e., treatments, tests and problems). State-of-the-art concept extraction approaches heavily rely on handcrafted features and domain-specific resources which are hard to collect and define. For this reason, this paper proposes an alternative, streamlined approach: a recurrent neural network (the bidirectional LSTM with CRF decoding) initialized with general-purpose, off-the-shelf word embeddings. The experimental results achieved on the 2010 i2b2/VA reference corpora using the proposed framework outperform all recent methods and ranks closely to the best submission from the original 2010 i2b2/VA challenge.

**Comment by cgreene** [comment]
This is a short paper that employs an LTSM network with random, Word2Vec, and GloVe embeddings. Performance is generally strong without hand-tuning or hand-constructed features applied on top of embeddings, though even the best LTSM method was pareto dominated by existing methods (i.e. there are methods that are better in both precision and recall). I'll probably mention it but it's definitely not transformative over existing approaches. Of note, the authors provide source code for the analyses.

**Comment by gwaygenomics** [comment]
> Of note, the authors provide source code for the analyses.

This could be something we stress heavily in the discussion about progressing the field. Made me think of a [tweet](https://twitter.com/StevenNHart/status/810890707158319106) I saw today about #159

**Comment by cgreene** [comment]
@gwaygenomics : I like the idea of noting exactly which contributions have provided source code. That might be loads of work though...

**Comment by cgreene** [comment]
@gwaygenomics : can you also note that tweet in the #159 discussion?

**Comment by cgreene** [comment]
Might as well provide the link to the code here in case someone comes along later and wants it:

https://github.com/raghavchalapathy/Bidirectional-LSTM-CRF-for-Clinical-Concept-Extraction

**Comment by cgreene** [comment]
I guess this means we can tag @raghavchalapathy also!

**Comment by cgreene** [comment]
Discussed in #167
