### ISSUE TITLE
Adversarial Deep Structural Networks for Mammographic Mass Segmentation

### ISSUE THREAD

**Issue by agitter** [greenelab/deep-review#164]
https://doi.org/10.1101/095786

> Mass segmentation is an important task in mammogram analysis, providing effective morphological features and regions of interest (ROI) for mass detection and classification. Inspired by the success of using deep convolutional features for natural image analysis and conditional random fields (CRF) for structural learning, we propose an end-to-end network for mammographic mass segmentation. The network employs a fully convolutional network (FCN) to model potential function, followed by a CRF to perform structural learning. Because the mass distribution varies greatly with pixel position, the FCN is combined with position priori for the task. Due to the small size of mammogram datasets, we use adversarial training to control over-fitting. Four models with different convolutional kernels are further fused to improve the segmentation results. Experimental results on two public datasets, INbreast and DDSM-BCRP, show that our end-to-end network combined with adversarial training achieves the-state-of-the-art results.

Relates to #163

**Comment by cgreene** [comment]
Performance is comparable to #168. Differences here are the addition of adversarial training to deal with the low sample number, and an alternative NN architecture. Ultimately, the results are relatively similar (especially given the small number of available training examples, it is hard to interpret differences on this scale).

**Comment by cgreene** [comment]
discussed in latest commits
