### ISSUE TITLE
Deep Learning for Drug-Induced Liver Injury

### ISSUE THREAD

**Issue by cgreene** [greenelab/deep-review#17]
https://dx.doi.org/10.1021/acs.jcim.5b00238

**Comment by cgreene** [comment]
This one is a bit more chemistry than most of what we're considering. It also lacks comparisons to other computational approaches. I'm going to close this for now. If you're interested in seeing this in the review, please comment & re-open.

**Comment by enricoferrero** [comment]
This *might* fit in the drug repositioning section but it's a bit of a stretch.

**Comment by agitter** [comment]
You could leave it out in the initial draft and see if it makes sense to add it in a second pass.  We haven't felt the need to cover every interesting deep learning paper in an area and have been trying to focus only a subset that advance the main conclusions we want to propose.

If you do decide to include this, you can refer back to my quick description of #232 elsewhere in the Treat section that they use to encode molecules.
