### ISSUE TITLE
Augmented Training Data List

### ISSUE THREAD

**Issue by cgreene** [greenelab/deep-review#172]
Papers that use augmented training data. @agitter had a great suggestion that we maintain this to help us with subsequent discussion.

**Comment by cgreene** [comment]
#163 #99

**Comment by agitter** [comment]
#117 only has positive instances in the training data and generates synthetic negative instances

**Comment by agitter** [comment]
Imputation in #197 could be related

**Comment by agitter** [comment]
Closed, see #367
