### ISSUE TITLE
De novo identification of replication-timing domains in the human genome by deep learning

### ISSUE THREAD

**Issue by cgreene** [greenelab/deep-review#18]
https://dx.doi.org/10.1093/bioinformatics/btv643

**Comment by cgreene** [comment]
Took a quick look at the paper. I don't know enough about replication timing to know of immediate examples where this has the type of translational relevance that our review is aiming for. Will close for now - feel free to reopen if you feel that I'm mistaken.

**Comment by agitter** [comment]
@cgreene There is a link between replication timing and somatic mutations (http://doi.org/doi:10.1038/ncomms2502).  Arguably, better understanding replication timing could help interpret cancer genomes.  But I didn't read this paper to see whether there really is any connection between the model here and disease interpretation.
