### ISSUE TITLE
Do you want to include chemistry/drugs?

### ISSUE THREAD

**Issue by swamidass** [greenelab/deep-review#187]
I have a large number of references I can provide if that is an interesting direction.

**Comment by agitter** [comment]
Yes, we definitely do want to cover this.  Thanks for your interest, this is why we wanted to write the review in the open.

Please see #174 in which I cataloged all of the papers related to high-throughput chemical screening and drug discovery that currently have issues open.  You can open new issues and reference them in #174 for missing papers.  I'd like to write this section in the next week or so, so this is a perfect time to discuss this body of work.  My initial thoughts are outlined in [my updated version of the Treat section](https://github.com/greenelab/deep-review/blob/21c9ac97a157479e6bb902ca1c136b0c691cc533/sections/05_treat.md).

It is hard to say what we want to be in or out of scope for this section, so if you truly have a huge number of new papers it could be a good idea to discuss the goals of this section before you spend a lot of time creating issues.  Nothing is set in stone at this point.

**Comment by swamidass** [comment]
Okay, perhaps the first step is give you a list of some of the most important citations you missed. From there, we could have a "scoping" citation. I'm at PSB right now, but will try and get you something by early next week.

**Comment by agitter** [comment]
Closing this.  We'll continue the discussion in #174.
