### ISSUE TITLE
Overall Manuscript Structure

### ISSUE THREAD

**Issue by cgreene** [greenelab/deep-review#2]
The overall aims of the Headline Review articles are outlined in the README. Here's a document structure that I am playing around with to target the review at this question: *What would need to be true for deep learning to transform how we categorize, study, and treat individuals to maintain or restore health?*

* Relevant areas where methods inspired by deep learning are already having an impact
    * Sequence -> Function
    * Transcriptional regulation
    * Patient information
    * Imaging + Bio
* The structures of problem statements which use deep learning towards these ends
    * Supervised approaches
        * Convolutional NNs on genome
        * Principles in which multiple synergistic patterns are learned simultaneously
        * more examples of shared properties across approaches
    * Unsupervised approaches
        * some denoising autoencoder work is common across systems
        * more shared properties
* Perspectives towards the future & overall question.
    * Which challenges do we think will be resolved first?
    * Are there any approaches/data types that have taken off in other fields but that are under-utilized here?
    * What initiatives or data do we think are particularly interesting for/amenable to deep learning analyses and why?
* Overall summary on state of the field & reflection towards overall question.

There are some wonderful github-based reading groups/lists by @pimentel @hussius @gokceneraslan. If any of you have feedback as we structure this review, please provide it. If you'd like to participate - dive in!

**Comment by cgreene** [comment]
Also wanted to tag @YosephBarash and @davek44 who have been active in this area for their thoughts.

**Comment by michaelmhoffman** [comment]
What is the format of the text itself? GitHub markdown?

**Comment by michaelmhoffman** [comment]
Does this need to actually have anything to do with "systems pharmacology"?

**Comment by cgreene** [comment]
@michaelmhoffman It should probably roughly touch on topics that could be construed as systems pharmacology. My read is that the precision medicine perspective + deep learning on genomic/transcriptomic/proteomic/etc data gets us close enough.

Format of the text itself will be markdown [eventually I'll convert it to LaTeX and reformat]. I think we will use something like [@doi:<doi link>] for citations. @dhimmel has code to automatically pull down doi metadata and covert to bibtex.

**Comment by agitter** [comment]
> Are there any approaches/data types that have taken off in other fields but that are under-utilized here?

Reinforcement learning perhaps?  http://karpathy.github.io/2016/05/31/rl/ gives a brief intro.  I'm not aware of examples in biology or medicine.

**Comment by michaelmhoffman** [comment]
Reinforcement learning hooked up to some experimental system would be fun.

**Comment by dhimmel** [comment]
> @dhimmel has code to automatically pull down doi metadata and covert to bibtex.

@cgreene, the [code is here](https://gist.github.com/dhimmel/719fc5e3a21dd2779d9fe69bf41e6ba6). Let me know when formatting time comes and I can help with the auto-conversion of citations.

**Comment by agitter** [comment]
@dhimmel that looks great.  May want to pair it with [Arxiv2bib](http://nathangrigg.github.io/arxiv2bib/) at formatting time.

**Comment by dhimmel** [comment]
@agitter thanks! How about the following citation conventions:

1. Always use a DOI for the version of record if available. Cite DOIs using `[@doi:10.15363/thinklab.4]`
2. If no DOI for the version of record, use a PubMed ID. For example, `[@pmid:26158728]`.
3. If the article is an arxiv preprint, use `[@arxiv:1508.06576]`.
4. If the article has none of the above, big problem. File an issue.

You can do multiple citations using: `[@doi:10.15363/thinklab.4 @pmid:26158728 @arxiv:1508.06576]`

**Comment by cgreene** [comment]
@dhimmel proposed citation conventions look good to me. Do you want to file a PR to add it to the contribution instructions?

**Comment by agitter** [comment]
@cgreene there are a lot of **Imaging + Bio** deep learning papers out there.  Should we take a more targeted approach for logging them as issues, such as focusing on those that pertain to human disease and medicine, instead of trying to catalog everything?  What might be the main points of this subsection?

**Comment by cgreene** [comment]
@agitter : I guess I'd say, if one could make an argument that it's relevant to our current guiding question [which I think still needs a bit of refinement - but probably an increase in specificity, not a decrease] then those are the ones for which we should file an issue.

**Comment by cgreene** [comment]
Going to close this now that the discussion has been captured in subsequent issues.

**Comment by agitter** [comment]
@dhimmel This issue was closed, but I wanted to ask a follow up question now that we're starting to write.  The citation conventions above will be great for making the citations machine-readable for automated bibliography construction.  Do you have any ideas for how to make them human-readable as well?  For example, in latex/bibtex I might use `\cite{Zhou2015_deep_sea}` so that anyone reviewing my text knows which paper I'm discussing.  That will be harder to do when reviewing DOIs and PMIDs.

**Comment by dhimmel** [comment]
> Do you have any ideas for how to make them human-readable as well?

DOIs have some semantic meaning (often contain a journal abbreviation). But we could define another category such as `[tag:Zhou2015_deep_sea]` and then you'd also have to update a mapping file where `Zhou2015_deep_sea` would point to a valid machine-readable citation. Do you think that is a good solution?

**Comment by agitter** [comment]
@dhimmel yes, I think that would be the best solution for machine- and human-readable citations.  It adds overhead for the authors so we'll have to weigh those tradeoffs.

@cgreene do you have an opinion about creating a citation mapping file?

**Comment by cgreene** [comment]
I defer to you and Daniel.
