### ISSUE TITLE
TensorFlow: Biology’s Gateway to Deep Learning?

### ISSUE THREAD

**Issue by cgreene** [greenelab/deep-review#21]
https://dx.doi.org/10.1016/j.cels.2016.01.009

**Comment by michaelmhoffman** [comment]
This is a News and Views piece or microreview.

**Comment by agitter** [comment]
It's a nice quick overview, but I think it is out of scope for this review.  @michaelmhoffman do you agree?

**Comment by michaelmhoffman** [comment]
@agitter There might be useful stuff to be gained but I would suggest reviews (including this one) be triaged until after analysis of primary research papers and maybe even the paper is written. Could be used to identify gaps that maybe should be filled. I can't promise I fully understand exactly what the scope is here though :)

**Comment by cgreene** [comment]
Likely out of scope.
