### ISSUE TITLE
Protein Fold Recognition with Representation Learning and Long Short-Term Memory

### ISSUE THREAD

**Issue by agitter** [greenelab/deep-review#211]
http://doi.org/10.2197/ipsjtbio.10.2

> Predicting the 3D structure of a protein from its amino acid sequence is an important challenge in bioinformatics. Since directly predicting the 3D structure is hard to achieve, classifying a protein into one of the “folds”, which are pre-defined structural labels in protein databases such as SCOP and CATH, is generally used as an intermediate step to determine the 3D structure. This classification task is called protein fold recognition (PFR), and much research has addressed the problem of either (i) feature extractions from amino acid sequences or (ii) classification methods of the protein folds. In this paper, we propose a new approach for PFR with (i) learning feature representations with unsupervised methods from a large protein database instead of manual feature selection and using external tools. (ii) learning deep neural architectures, recurrent neural networks (RNNs) with long short-term memory (LSTM) units, and re-training the representations instead of fixing the extracted features. On a benchmark dataset, our approach outperforms existing methods that use various physicochemical features.

@j3xugit Any thoughts on the relevance of this?

**Comment by j3xugit** [comment]
The method itself may be interesting, but the experimental design of this paper is very bad.
The authors tested their algorithm on only 27 folds, while currently there are about 1000 different folds in PDB. When we do protein fold recognition, we have to consider all the possible folds instead of just 27 folds. It is unclear if the proposed algorithm can scale up to 1000 folds or not.

**Comment by agitter** [comment]
Thanks for the quick comment.  We have enough other interesting methods to cover so I'm going to close this issue.
