### ISSUE TITLE
Accurate prediction of single-cell DNA methylation states using deep learning

### ISSUE THREAD

**Issue by traversc** [greenelab/deep-review#244]
http://biorxiv.org/content/biorxiv/early/2016/05/27/055715.full.pdf

> Recent technological advances have enabled assaying DNA methylation in single cells. Current protocols are limited by incomplete CpG coverage and hence methods to predict missing methylation states are critical to enable genome-wide analyses. We here report DeepCpG, a computational approach based on deep neural networks to predict DNA methylation states from DNA sequence and incomplete methylation profiles in single cells. We validate DeepCpG on mouse embryonic stem cells, where we report substantially more accurate predictions than previous methods. Additionally, we show that DeepCpG provides new insights for interpreting the sources of epigenetic diversity. Our model can be used to estimate the effect of single nucleotide changes and we uncover sequence motifs that are associated with DNA methylation level and epigenetic heterogeneity.

In this paper they use convolutional neural networks.  One of the interesting points that caught my attention is that they claim to discover novel sequence motifs associated with DNA methylation.

**Comment by agitter** [comment]
This is an updated version of #39.  I'm closing this so we can keep the discussion in one place.
