### ISSUE TITLE
Deep Learning in Bioinformatics

### ISSUE THREAD

**Issue by cgreene** [greenelab/deep-review#27]
http://arxiv.org/abs/1603.06430

**Comment by agitter** [comment]
The published version appeared recently http://doi.org/10.1093/bib/bbw068

**Comment by gwaygenomics** [comment]
Another wide-net-casting review (225 references!). Very similar to #47 and #28. Structure is as follows:

1. Introduce MLP, CNN, RNN, and "emergent architechtures"
2. Review each of these deep learning techniques in the following bioinformatics topics
  * Omics
  * Imaging
  * Signal processing (e.g. EEG)
 3. Discussion

Their discussion is also broken up into sections that we've seen before:

1. Limited and imbalanced data
  * Very similar to the discussion [here](https://github.com/greenelab/deep-review/issues/43#issuecomment-238485877) in #43 
2. Black-box algorithms
  * Similar to #28 
  * Do provide some insight into "changing the black-box into the white-box"
3. Hyperparameter selection difficulty
4. Multimodal deep learning
  * Data integration
  * Very limited discussion that we can greatly expand upon
5. Accelerating deep learning
  * discusses optimization strategies
  * computational hurdles, etc.
6. Future of deep learning
  * they do briefly touch upon how they view unsupervised tasks as gaining traction
  * e.g. Adversarial Nets

**Comment by gwaygenomics** [comment]
based on the past couple reviews I've read there doesn't appear to be too much niche carving...they all are quite similar although they claim to offer unique perspectives (or omit citations to alternative reviews all together). 

I think we should try to carve a niche - not sure what it could be yet though

**Comment by agitter** [comment]
Cited in the intro
