### ISSUE TITLE
Hyperlink DOI/URL citations in gh-pages

### ISSUE THREAD

**Issue by gwaygenomics** [greenelab/deep-review#271]
It would be great if after a travis build, URLs or DOIs are embedded as hyperlinks in the inline citations in the markdown rendering. I think this would make the gh-pages more useful, but I am not sure how hard this would be to do. @dhimmel perhaps you would have a better idea of the feasibility

**Comment by dhimmel** [comment]
@gwaygenomics see the current manuscript and PDF. The reference numbers now link to the bibliographic item. I know you wanted the link to go to the actual cited document. This is something that we can look into in the future. If it's possible using CSL that would be ideal.

**Comment by gwaygenomics** [comment]
wow! This is great. I'll close this issue for now to keep them focused on papers but we can keep that next step in mind
