### ISSUE TITLE
Applications of deep learning in biomedicine

### ISSUE THREAD

**Issue by cgreene** [greenelab/deep-review#28]
https://dx.doi.org/10.1021/acs.molpharmaceut.5b00982

**Comment by gwaygenomics** [comment]
Another good review that casts a broad net of deep learning applications. The structure of the review focuses much more on these applications than algorithm specifics.

The authors focus on genomic (e.g. NGS), transcriptomic (e.g. lncRNA expression), proteomic, structural biology/biochem, and drug repurposing as application areas. They cite one or two of he most prominent examples of deep learning applied to each subject area in each respective section. We already have issues for every example they cite. 

They also have a nice, but brief, discussion about deep learning challenges - which they describe as:

1. Black box problem
  * hard to interpret learned functions in biology (much harder than image/speech/text/etc.)
2. Need for large datasets
  * much risk for overfitting
3. Selection problem
  * Often difficult to match the appropriate algorithm with the task at hand
4. Computation Costs

They end with a limited discussion about future directions. They focus on three points:

1. The promise of drug repurposing
2. Availability of lots of transcriptomic data
3. The need for increased collaboration between biologists and computational people

Overall, I think it complements #47 nicely by structuring the review by genomic platform. It also discusses  biomedical applications and cancer in more detail than #70

**Comment by agitter** [comment]
Challenge 1 (black box) could be worth discussing in the review because this point comes up a lot.  Especially if @akundaje is contributing and could preview the updated DeepLIFT (#50).  @cgreene could also present strategies for interpreting hidden units in autoencoders for gene expression.

**Comment by agitter** [comment]
Cited in the intro
