### ISSUE TITLE
Still need more papers?

### ISSUE THREAD

**Issue by fairmiracle** [greenelab/deep-review#281]
Just come by to see this..I starred two repositories about deep learning in computational biology and contributed one of them. Hope it can help:
https://github.com/hussius/deeplearning-biology
https://github.com/fairmiracle/awesome-deepbio

What is the current stage of this collaboration? Still need contribution?

**Comment by fairmiracle** [comment]
you mentioned this reivew is  inspired by a collection of deep learning papers, here are two more popular ones (see the star number):
https://github.com/songrotek/Deep-Learning-Papers-Reading-Roadmap
https://github.com/terryum/awesome-deep-learning-papers

**Comment by agitter** [comment]
I believe that @cgreene pulled papers from those two deep learning in computational biology repositories when he first created our issues, but we haven't be synchronizing regularly.

We do still need help with the paper.  At this point, I'd say the greatest need is in organizing and reviewing papers and drafting the sections in https://github.com/greenelab/deep-review/tree/master/sections.  It is useful to catalog additional relevant papers as issues, but we have a massive backlog to go through, prioritize, and discuss in the review.  If there is a particular topic you're interested in, please do join in.  We also have a stale status report in #188 showing areas of need.

**Comment by cgreene** [comment]
Hi @fairmiracle : feel free to add and summarize more specific papers. We may or may not write them into the paper, but it turns out the collaborative discussion here seems to be something that people enjoy. I agree with @agitter's discussion of #188 if you wish to contribute to the review.

**Comment by cgreene** [comment]
In the interest of issue pruning, I'm going to go ahead and close this. @fairmiracle please drop by #188 if you're interested.
