### ISSUE TITLE
Automatic github.io build does not display multiple sources in citations

### ISSUE THREAD

**Issue by gwaygenomics** [greenelab/deep-review#290]
Just noticed this today - multiple sources listed in a citation do not appear in https://greenelab.github.io/deep-review/

See example [here](https://github.com/greenelab/deep-review/blob/master/sections/03_categorize.md#temporal-patient-trajectories) and second paragraph of [here](https://github.com/greenelab/deep-review/blob/master/sections/04_study.md#gene-expression)

They do appear to be tracked in the references section. Not sure if this has been discussed before.

@dhimmel, do you know of a solution?

**Comment by dhimmel** [comment]
Wow that's a big problem. I'll investigate. Since the references are getting a number and being included in the bibliography, I'm guessing it's a pandoc problem. Will investigate.
