### ISSUE TITLE
In silico Pathway Activation Network Decomposition Analysis (iPANDA) as a method for biomarker development

### ISSUE THREAD

**Issue by enricoferrero** [greenelab/deep-review#316]
https://doi.org/10.1038/ncomms13427 (https://www.nature.com/articles/ncomms13427)

> Signalling pathway activation analysis is a powerful approach for extracting biologically relevant features from large-scale transcriptomic and proteomic data. However, modern pathway-based methods often fail to provide stable pathway signatures of a specific phenotype or reliable disease biomarkers. In the present study, we introduce the in silico Pathway Activation Network Decomposition Analysis (iPANDA) as a scalable robust method for biomarker identification using gene expression data. The iPANDA method combines precalculated gene coexpression data with gene importance factors based on the degree of differential gene expression and pathway topology decomposition for obtaining pathway activation scores. Using Microarray Analysis Quality Control (MAQC) data sets and pretreatment data on Taxol-based neoadjuvant breast cancer therapy from multiple sources, we demonstrate that iPANDA provides significant noise reduction in transcriptomic data and identifies highly robust sets of biologically relevant pathway signatures. We successfully apply iPANDA for stratifying breast cancer patients according to their sensitivity to neoadjuvant therapy.

Not sure if this has been considered before? It's basically the method that has been used in #162 and could be introduced in a bit more detail in the treat section (subsection efficient clinical trials) - Happy to help if of interest!

**Comment by agitter** [comment]
I only skimmed this, but are they using deep learning?  I saw

> Thus, using the iPANDA signalling pathway activation scores as input for deep learning methods could bring results closer to experimental settings and make them more interpretable to bench biologists.

but the methods looked like the current version uses random forests.

**Comment by enricoferrero** [comment]
You're right - they mention deep learning but the implementation appears to be random forests. I've heard from the authors and understood that the *current* version of iPANDA is implemented  with DNN but the paper probably refers to a previous version.
