### ISSUE TITLE
abbreviations: DNN, CNN, RBM, DBN, etc

### ISSUE THREAD

**Issue by alxndrkalinin** [greenelab/deep-review#345]
Couldn't find any guidelines on abbreviations - are we going to introduce common ones like CNN in the beginning of the manuscript and use further on? Is there journal policy on this?

**Comment by agitter** [comment]
Good question.  We haven't decided anything yet.  Defining the most common neural network abbreviations like those in the issue title in the introduction makes sense.  Others can be defined at first use.

@cgreene let us know if you have thoughts.

**Comment by cgreene** [comment]
NDC -> National Drug Codes (came up in #339)

ICD -> International Classification of Diseases

I figure we'll need to go through and define acronyms the first time they appear. If you encounter some, feel free to note them here.

**Comment by enricoferrero** [comment]
NLP: natural language processing (#342).
Plan to introduce it in Categorize/EHR, I can see it's also used in Study/Metagenomics.

**Comment by agitter** [comment]
RF -> random forest

May decide to always write it out in full, but we should be consistent throughout.

**Comment by agapow** [comment]
What I've spotted that appear to occur more than once:

EHR: electronic health record
RNN: recurrent NN
TF: transcription factor
MRI / fMRI: Magnetic resonance imaging
DBM: deep boltzman machine
DBN: deep belief network
MTL: multi-task learning

**Comment by agitter** [comment]
AUC: area under the curve
ROC: receiver operating characteristic

Needed for #438 among others

**Comment by agitter** [comment]
I'm going through these in #498 and adding 👍 once I cover them.

**Comment by agitter** [comment]
Instead of abbreviating random forest as RF, which I don't care for, I'm using square brackets to write it out in a quote.  This will show up as a warning during builds, but we can ignore it.
