### ISSUE TITLE
Move data sharing paragraph

### ISSUE THREAD

**Issue by agitter** [greenelab/deep-review#348]
In planning the "Code, data, and model sharing" sub-section of Discussion, I realized it would be helpful to move the "research parasites" text here.  @cgreene if you agree can you please move the Categorize paragraph starting with "In addition to methodological improvements" to Discussion?  I can do it myself but thought your Categorize section might also need to be modified to link the data sharing discussion there with the relevant Discussion sub-section.

**Comment by agapow** [comment]
This may have been reintroduced with my merge on the categorize section. Mea culpa. I can rip it out if need be.
