### ISSUE TITLE
Denoising genome-wide histone ChIP-seq with convolutional neural networks

### ISSUE THREAD

**Issue by cgreene** [greenelab/deep-review#35]
https://doi.org/10.1093/bioinformatics/btx243 (previously https://doi.org/10.1101/052118)

> Motivation: Chromatin immune-precipitation sequencing (ChIP-seq) experiments are commonly used to obtain genome-wide profiles of histone modifications associated with different types of functional genomic elements. However, the quality of histone ChIP-seq data is affected by many experimental parameters such as the amount of input DNA, antibody specificity, ChIP enrichment and sequencing depth. Making accurate inferences from chromatin profiling experiments that involve diverse experimental parameters is challenging.
Results: We introduce a convolutional denoising algorithm, Coda, that uses convolutional neural networks to learn a mapping from suboptimal to high-quality histone ChIP-seq data. This overcomes various sources of noise and variability, substantially enhancing and recovering signal when applied to low-quality chromatin profiling datasets across individuals, cell types and species. Our method has the potential to improve data quality at reduced costs. More broadly, this approach—using a high-dimensional discriminative model to encode a generative noise process—is generally applicable to other biological domains where it is easy to generate noisy data but difficult to analytically characterize the noise or underlying data distribution.
Availability and implementation: https://github.com/kundajelab/coda.

**Comment by agitter** [comment]
Updated the post above with the published version.  We can switch to the new DOI in the review.
