### ISSUE TITLE
Dropping subsections

### ISSUE THREAD

**Issue by agitter** [greenelab/deep-review#352]
April 24, our stated date for dropping undrafted sub-sections, has arrived.  After scanning the open pull requests and remaining undrafted sub-sections in the outline, I propose we drop the following:

- Categorize
    - Has deep learning already induced a strategic inflection point for one or more aspects?
    - Will deep learning induce a strategic inflection point for categorization?
    - What unique potential does deep learning bring to this?
    - Where would you point your deep learning efforts if you had the time?
- Study
    - RNA-binding proteins
    - Signaling
- Treat
    - Modeling Metabolism and Chemical Reactivity

We don't have a miRNA binding draft in place, but @bdo311 has been writing excellent sections so I'd like to extend the deadline for that topic.

There are still several miscellaneous Discussion topics to cover as well as the abstract and conclusions.  Still, there has been amazing progress in the past two weeks!

**Comment by cgreene** [comment]
I agree & will go ahead and file a PR on this if I get the chance today - if not today, then early tomorrow. If anyone else wants to file, feel free to go ahead.

**Comment by agapow** [comment]
I don't think any of the missing sections are critical - a line has to be drawn somewhere or that paper could go on forever.  RNA-binding proteins must overlap heavily with other areas.

**Comment by agitter** [comment]
I'm going to work on merging our existing pull requests before dropping some of these.  For something like RNA binding proteins, I may want to add a line in the TF binding section pointing out this related, but somewhat different problem, that we didn't cover.

**Comment by cgreene** [comment]
I think that for the categorize section this is fixed. I will reassign to @agitter to close when the other sections are appropriately handled.
