### ISSUE TITLE
Consistency of terms & wording & style

### ISSUE THREAD

**Issue by agapow** [greenelab/deep-review#391]
Some terms or phrases are used in varying ways through the ms. This can be fixed late, but for reference, I've spotted:

* deep learning / Deep Learning / DL / "deep leaning methods"
* healthcare / health care
* significant (should really be reserved for statistical significance)
* omics, -omics
* "e.g." or "e.g.," (trailing comma)
* "i.e." or "i.e.,"
* multitask, multi-task
* multimodal, multi-modal
* "et al", "et al."
* oxford commas

**Comment by enricoferrero** [comment]
Good catch. My preferences:
- deep learning
- healtcare
- omics

The other thing to check would be AE vs BE. I tried to conform to AE but might have used BE here and there (e.g.: colour, categorisation).

**Comment by agapow** [comment]
Agree on all points. But the main thing is to be consistent.

**Comment by agitter** [comment]
Agreed, we should work on standardization.  This is fairly late in the submission timeline so if you catch these please submit small pull requests.  If you can submit minor pull requests that touch a few lines or a few paragraphs and only grammar and spelling, I'll review and merge them quickly.

In #347 we agreed on "multimodal" and "multi-task".  Despite the inconsistency, this is how they were used in the literature.

**Comment by agapow** [comment]
"significant" is a major irritation, couldn't judge for a lot of them. Fixed most others.

**Comment by agitter** [comment]
>"significant" is a major irritation, couldn't judge for a lot of them. Fixed most others.

I fixed a few more in #499, but like @agapow there are some I can't judge.
