### ISSUE TITLE
Reword and recite "Temporal Patient Trajectories" to "Applications of Deep Learning to Longitudinal Analysis"

### ISSUE THREAD

**Issue by aaronsheldon** [greenelab/deep-review#405]
In Section 3, the use of the phrase "temporal patient trajectories" is divergent from the medical, bio-statistical, and epidemiological literature. Consider a title such as "Applications of Deep Learning to Longitudinal Analysis", as this will create a bridge to the existing literature on the progression of health status and the process of healthcare delivery.

Furthermore, the first sentence is non-sequitur to the paragraph, as physician training has no bearing on the Deep Learning literature. Something along the lines would be better suited:

"Traditional longitudinal analysis of large population cohorts, either followed from birth, or from the onset of particular conditions, have provided important insights into the development of disease, and the factors contributing to health status [insert references to US and UK pop health cohorts]. Yet, a common practice... "

**Comment by cgreene** [comment]
Can you file a PR on these? :+1:

**Comment by aaronsheldon** [comment]
will do
