### ISSUE TITLE
"Defining deep learning"

### ISSUE THREAD

**Issue by davharris** [greenelab/deep-review#421]
I think that this section doesn't quite accomplish what it should, in terms of highlighting deep learning's distinctive features and its relationship to "shallow" approaches that readers might be familiar with.  I have a small outline below.

I've tried rewriting it a few times, but I'm feeling stuck.  If someone agrees that these would be improvements and wants to try them out, go for it.  Otherwise I'll try again in a few days.

* Should mention the key features of deep learning, compared to other methods: 
    * composition simple functions in "layers"
    * differentiability/backpropagation (in most cases)
    * automated feature engineering
* Should clarify that deep learning does many of the same jobs as more familiar approaches, such as clustering, regression/classification. It just has the potential to do them better because (with sufficiently large data sets) these models can learn which features to use.
* This is very minor, but I think that the current wording implies that autoencoders are "new"

**Comment by agitter** [comment]
At one point we had a version of the intro that included some of these ideas, but in a fairly technical way that may not have been useful for our audience.  In #382 @cgreene worked to merge two versions of the intro, and we stripped out the more technical parts.

I agree that the points above will be important for someone new to deep learning to understand some of the excitement that surrounds it.  If you do write something, I suggest trying to keep it to a single paragraph.  It could follow your existing outline closely.

**Comment by cgreene** [comment]
I agree - we lost this & it would be really nice to have.
