### ISSUE TITLE
Missing author approval

### ISSUE THREAD

**Issue by agitter** [greenelab/deep-review#446]
There are still several contributors who have not added themselves to the author list, and I want to make sure no one missed the readme update.  Contributors must approve the manuscript by Noon Eastern Time on May 17 to be included as co-authors.  File a pull request to add the appropriate line to `author_contact_approval.md`

We're missing approval from:
- @dhimmel
- @traversc
- @swamidass
- @jacklanchantin
- @XieConnect

**Comment by agitter** [comment]
@mrwns please let us know (today if possible) if you prefer to be added as an author or acknowledged for your help.  I consider your revisions to be a substantial intellectual contribution.

**Comment by agitter** [comment]
Tagging @AvantiShri and @jisraeli for authorship as well.

**Comment by mrwns** [comment]
thanks @agitter ! i have submitted a pull request #462

**Comment by jisraeli** [comment]
Thanks, I submitted PR #463

**Comment by XieConnect** [comment]
Thanks @agitter . I have just submitted a pull request of author approval: 
https://github.com/greenelab/deep-review/pull/471
