### ISSUE TITLE
Virtual Screening: A Challenge for Deep Learning

### ISSUE THREAD

**Issue by cgreene** [greenelab/deep-review#45]
https://dx.doi.org/10.1007/978-3-319-40126-3_2

**Comment by agitter** [comment]
I'm familiar with some of the deep learning approaches in this domain and can provide comments.  There is probably some overlap between the primarily literature discussed in this chapter and the review in #23.  I can also dig through my own stack of papers to add some additional ones related to virtual screening.

**Comment by cgreene** [comment]
@agitter That would be great! I've been adding an issue for each paper thus far.

**Comment by agitter** [comment]
I added a batch of virtual screening papers and had them all reference this issue.
