### ISSUE TITLE
Deep learning for computational biology

### ISSUE THREAD

**Issue by cgreene** [greenelab/deep-review#47]
http://doi.org/10.15252/msb.20156651

**Comment by lzamparo** [comment]
This one looks pretty complete, it's definitely on my reading list.

**Comment by gwaygenomics** [comment]
read this recently - it is a  well written article which casts a wide net around deep learning in biology but does not go into much detail on any particular method or application. I still haven't read #28 yet, but I think our goal (outlined in #2 and tagline pasted below) will be unique

> What would need to be true for deep learning to transform how we categorize, study, and treat individuals to maintain or restore health?

**Comment by akundaje** [comment]
This is a very good review. Definitely very accessible.

**Comment by agitter** [comment]
One question for the outline in #2 is how much deep learning background needs to be covered.  As @akundaje points out, this MSB review is very accessible and does a good job with background concepts.  Do they need to be discussed again to reach a broad audience?

**Comment by cgreene** [comment]
@agitter : Where there's a solid review like this, I would usually prefer to refer readers to it for a broad overview. This lets us focus on precisely the area we want to target. In practice, we'll need to give enough of an overview on our topic that we'll probably end up discussing some of the same points, but I don't think we need to do this kind of broad survey.

**Comment by agitter** [comment]
A great review, which we cited
