### ISSUE TITLE
Switch to preferred DOI resolution URLs

### ISSUE THREAD

**Issue by dhimmel** [greenelab/deep-review#48]
I noticed you were using DOI links in issues to refer to papers. This is great, but I noticed you were including `dx.` in the URLs which works but is deprecated.

So for example:

https://dx.doi.org/10.1093/bioinformatics/btw252

can be shortened to 

https://doi.org/10.1093/bioinformatics/btw252

More details from the [DOI handbook](https://www.doi.org/doi_handbook/3_Resolution.html):

> Users may resolve DOI names that are structured to use the DOI system Proxy Server (http://doi.org (preferred) or http://dx.doi.org). The resolution of the DOI name in this case depends on the use of URL syntax: the example DOI name doi:10.10.123/456 would be resolved from the address: "http://doi.org/10.123/456". Any standard browser encountering a DOI name in this form will be able to resolve it. The proxy service (both doi.org and dx.doi.org) is accessible over IPv6, and supports DNSSEC. The proxy servers respond to HTTPS as well as HTTP requests.

**Comment by dhimmel** [comment]
For future referrence... not suggesting you should go and change all of the existing issues :smile_cat:.

**Comment by cgreene** [comment]
The first batch of links was snagged from the "awesome-deepbio" list. It might be good to push this information upstream as it would be a simple fix there:
https://github.com/gokceneraslan/awesome-deepbio

Casey

**Comment by cgreene** [comment]
With this commit, upstream was fixed.
