### ISSUE TITLE
Has our enthusiasm tempered a bit?

### ISSUE THREAD

**Issue by cgreene** [greenelab/deep-review#495]
This came up here. 

https://github.com/greenelab/deep-review/pull/494#discussion_r117641573

**Comment by agitter** [comment]
The tone of the conclusion still matches my level of enthusiasm fairly well.  However, the tone varies throughout the manuscript.  In some sections we are careful to discuss limitations.  In others, we seem to stray too close to cheerleading.

I'm left wondering what our review says to the skeptic who has seen claims that various forms of AI will work alongside doctors or that machine learning will transform biology (e.g. accurately predict gene expression levels from sequence) time and time again and questions whether anything is different this time around.  I personally am very excited by the prospects for deep learning in the areas we reviewed.  But I also don't want to treat future transformations and "biological insights" (a term we may have overused) as inevitable.  As researchers, it's good to be enthusiastic, optimistic, and ambitious.  But going forward, we also need to demand rigorous evidence that improved predictive capabilities have actually been transformative, changed biological practice, affected patient outcomes, etc.

Depending on the responses here, I could draft a sentence or two for the conclusion to try to capture this sentiment.

**Comment by agapow** [comment]
Agreeing: the problem is not so much the level of the enthusiasm but more that fact that it varies from cautious to wildly exuberant.

**Comment by cgreene** [comment]
@agitter : I think that a sentence or two that summarizes what you're saying above would be perfect. Thanks!

**Comment by mrwns** [comment]
Yes, I agree there should be optimism with some healthy skepticism. The great thing about science, however, is that through experiments hype is easily debunked.

**Comment by agitter** [comment]
#497 is my attempt to present my thoughts above in the conclusions.  I welcome feedback.
