### ISSUE TITLE
The manuscript needs a title

### ISSUE THREAD

**Issue by cgreene** [greenelab/deep-review#496]
I'd love to snag a few proposals before I throw something out. We can work with and refine them. Tagging a few people who have been involved in the recent pull requests. Everyone should feel free to contribute though!
@agapow @alxndrkalinin @dhimmel @bdo311

**Comment by agitter** [comment]
Tagging @enricoferrero as well, he's been reviewing recent pull requests

**Comment by agapow** [comment]
Off the top of my head (probably more ideas tomorrow):

- Deep learning: the transformation of biomedicine?
- Deep learning and complex biomedical analysis
- Deep learning and applications in biomedicine
- Deep learning: a possible revolution in biomedical analysis?

**Comment by yfpeng** [comment]
Five years of deep leaning in biomedical analysis: where do we go from here?

**Comment by bdo311** [comment]
- The Promise and Challenges of Deep Learning in Biology and Medicine
- Digging "Deep" Into Biology and Medicine with Neural Networks

**Comment by cgreene** [comment]
Woo! Good ideas! I want to throw out there that we also wrote this paper in a bit of a unique way. Do we want to incorporate that into the title somehow? What would you term this? A Massively Open Online Review (MOOR) comes to mind along the lines of a MOOC, but I'm not sure we're quite at that scale.

**Comment by akundaje** [comment]
I like both of Brian's suggested titles.

-Anshul.

**Comment by agitter** [comment]
For reference, here are the titles of the related reviews we cite so we can avoid being too redundant:
- Deep learning for regulatory genomics
- Applications of Deep Learning in Biomedicine
- Deep learning for computational biology
- Deep learning in bioinformatics
- Computer vision for high content screening
- Deep learning for healthcare: review, opportunities and challenges
- Deep Learning in Drug Discovery
- Deep learning for computational chemistry
- Virtual Screening: A Challenge for Deep Learning
- A renaissance of neural networks in drug discovery

I suggest we avoid the "deep learning for/in X" style.  I'll work on my own suggestions.

(ignore my accidental close/reopen)

**Comment by alxndrkalinin** [comment]
I like the direction of `The Promise and Challenges of DL in ...`, it indicates a higher level review, not just literature survey (similar to #423, though).

Although I like the MOOR idea, I think this effort isn't at comparable scale. But we can indicate the approach by subtitle, e.g. something like:
* `The Promise and Challenges of Deep Learning in Biology and Medicine: A Collaborative Perspective`
* `The Promise and Challenges of Deep Learning in Biology and Medicine: A Review by Scientific Crowdsourcing`

**Comment by enricoferrero** [comment]
Very similar to the ones above:
> Promises and Challenges of Deep Learning in Biology and Medicine: A Collaboratively Written Review
> Promises and Challenges of Deep Learning Applications on Biomedical Data: A Collaboratively Written Review

**Comment by agitter** [comment]
> I want to throw out there that we also wrote this paper in a bit of a unique way. Do we want to incorporate that into the title somehow?

The collaborative style was essential for the review and a big part of why I wanted to get involved.  But is it the headline result?  If it is (and we may agree that it is), we should mention it in the abstract and introduction as well.  Currently we don't discuss the writing process until the Methods section.

**Comment by agapow** [comment]
I (weakly) favour leaving the collaborative aspect out of the title, just because it may distract from the important parts.

**Comment by agitter** [comment]
So far, my favorite is "The Promise and Challenges of Deep Learning in Biology and Medicine" from @bdo311, maybe with a synonym for "challenges" because it is used in #423.  Barriers?  Limitations?  Impediments?

**Comment by evancofer** [comment]
Opening Up Deep Learning: Opportunities and Obstacles in Biology and Medicine

Some variations:
Opening Up Deep Learning: Opportunities and Challenges in Biology and Medicine
Deep Learning: Opportunities and Obstacles Posed in Biology and Medicine
Opening Up Deep Learning: Opportunities and Challenges Posed by Biology and Medicine
Opening Up Deep Learning: Opportunities and Obstacles Posed by Biology and Medicine

**Comment by cgreene** [comment]
"The promise of and barriers to deep learning in biology and medicine"?

**Comment by bdo311** [comment]
Maybe "Opportunities and Obstacles for Deep Learning in Biology and Medicine"?

I still like "Digging "Deep" Into Biology and Medicine with Neural Networks" because punny titles are always appreciated..

**Comment by cgreene** [comment]
oo, I like opportunities and obstacles. :+1: I'm a bit reluctant to pun-ish our readers, but if everyone wants to we can go that route ;)

**Comment by agitter** [comment]
@bdo311 if you want puns, you've come the right place

Deep Learning in Biology and Medicine: The Doctor Will CNN You Now

**Comment by agitter** [comment]
More seriously, I also like the alliteration of opportunities and obstacles from @evancofer / @bdo311
