### ISSUE TITLE
Not Just a Black Box: Learning Important Features Through Propagating Activation Differences

### ISSUE THREAD

**Issue by agitter** [greenelab/deep-review#50]
https://arxiv.org/abs/1605.01713

**At a glance**: A strategy for interpreting neural networks, which could be an important topic in the review.  The paper is a technical description of a general method, but one subsection shows an application to genomics and there is more work coming from the Kundaje lab in this direction.

**Comment by akundaje** [comment]
We'll have an expanded version of this on Biorxiv in the next few weeks.

**Comment by cgreene** [comment]
@akundaje : Will you post here when it's up? Might put this one on hold & read the new one at the same time.

**Comment by akundaje** [comment]
@cgreene Yeah definitely. The current version is extremely succint (had to be that way due to conference format limitations). So the new expanded version will be much easier to read and understand.

**Comment by michaelmhoffman** [comment]
@akundaje: I just came across your DragoNN web site: http://kundajelab.github.io/dragonn/

Is this the same thing? Or is there another paper for that?

**Comment by cgreene** [comment]
I saw Anshul give a talk at the Simons Network Biology workshop. It may be
some of that work:
https://simons.berkeley.edu/talks-anshul-kundaje-04-13-16

Side note/shameless plug since I also gave a talk - there's actually a lot
of very nice talks. For all of the ones where the speaker gave permission,
the talks are recorded and available on youtube:
https://simons.berkeley.edu/workshops/schedule/1806

Casey

**Comment by akundaje** [comment]
@michaelmhoffman We have a different paper in submission for DRAGONN. It'll be up on archive by the weekend. DeepLIFT is provided in DRAGONN for identifying predictive features in the input sequences.

**Comment by akundaje** [comment]
@cgreene Yeah the Simon's meeting was really great.

**Comment by jbloom22** [comment]
Here is Anshul's [Nov 2 presentation](https://www.youtube.com/watch?v=CsYDUp-atu4) on this and related work from the [Models, Inference & Algorithms seminar](https://www.broadinstitute.org/mia) at the Broad Institute.

**Comment by akundaje** [comment]
@cgreene @agitter Here is our significantly expanded and updated preprint on DeepLIFT https://arxiv.org/abs/1704.02685 . Submitted to an ML conference. @AvantiShri made some great videos explaining DeepLIFT here http://goo.gl/qKb7pL . Updated code: http://goo.gl/RM8jvH.

**Comment by akundaje** [comment]
Also @cgreene @agitter we will finish a draft of the interpretation section by next week.

**Comment by agitter** [comment]
Thanks @akundaje.  @jacklanchantin can you please see if there are changes you'd like to incorporate into your DeepLIFT description?

Regarding interpretation, @blengerich wrote something in #312.  I propose moving that to the Discussion so you can use his text as a starting point.  I'll make a pull request.

**Comment by agitter** [comment]
The updated version is covered in the Discussion

**Comment by agitter** [comment]
@traversc noted that this was published in the ICML 2017 proceedings.  There is no DOI as far as I can tell:
http://proceedings.mlr.press/v70/shrikumar17a.html
