### ISSUE TITLE
PDF formatting

### ISSUE THREAD

**Issue by agitter** [greenelab/deep-review#516]
Does anyone have ideas to improve the pandoc-built PDF?  Is there a template we could use to reduce the page margins, reduce font size, add page numbers, etc.?

@dhimmel, I don't want this to delay submission or be a big time commitment.   I'm only interested if someone knows of a quick solution.

**Comment by dhimmel** [comment]
Agreed that some BAA (badass aesthetics) for the PDF (and even the HTML output) would be nice. I don't have time right now to really dig deep here. But I'd be happy to help implement a solution if someone finds a good one.

**Comment by agitter** [comment]
The superscripts I added to the HTML look quite bad.  I don't have time to work on this now either.  We can table it for later.

**Comment by dhimmel** [comment]
Maybe use a numbered list for defining the affiliations? Also consider using dagger `†` than than `+`

**Comment by dhimmel** [comment]
I'll make this PR right now

**Comment by evancofer** [comment]
It looks like pandoc can output LaTeX code from markdown (or at least that's what is says here: http://pandoc.org/). Depending on what is wanted, that may be the best format for spicing things up. There are also numerous professional templates available (see for examples: https://www.sharelatex.com/templates/journals).

**Comment by agitter** [comment]
@dhimmel Do you want me to do it?  I have a script that does 80% of the formatting?  It's not robust enough for the build process, but shortens the manual effort.

**Comment by agitter** [comment]
@evancofer That sounds promising.

**Comment by dhimmel** [comment]
@evancofer right now I think the PDF output is generated without Latex. Note that I don't have a full understanding of what pandoc is doing and how we can add additional formatting to the PDF.

It would be ideal to avoid use of latex, since it's an unwieldy dependency and is outdated. I'm worried that the latex dependency could drag down the HTML output, which I think is the most important format. One other option would be to save the HTML page as PDF. @agitter does that produce a nicer PDF then the direct pandoc export?

**Comment by dhimmel** [comment]
I should note that I'm not opposed to a Latex dependency to make a nice PDF as long as it doesn't remove features or create incompatibilities with the current HTML-first output.

**Comment by agitter** [comment]
@dhimmel I actually think our HTML output is slightly worse than the PDF right now because the superscripts are off.  We have one in the text as well, not just in the author list.

**Comment by evancofer** [comment]
I'm going to experiment with it a bit. I will let you know if it works and how the results look. If the PDF output looks nice, we can also convert the LaTeX to HTML with pandoc, latex2html (http://www.latex2html.org/), or a similar tool. It shouldn't interfere with the existing HTML output at all.

**Comment by evancofer** [comment]
Here's an example of what it might look like. This is more of a feasibility proof, so I kept the formatting rather simple. It should be noted that I have not yet attempted to implemented the references, so citations currently appear as raw text. I will try out latex2html on this later tonight.

[DeepReviewLaTeXTest.pdf](https://github.com/greenelab/deep-review/files/1030375/DeepReviewLaTeXTest.pdf)

**Comment by agitter** [comment]
@evancofer That looks promising.  The text layout looks better and the page numbers are helpful.  I think we should keep working on this but not let it delay the initial submission.  Resolving the references and templates (see page 87) will be non-trivial.

**Comment by dhimmel** [comment]
@evancofer you're going to want to use [`all-sections.md`](https://github.com/greenelab/deep-review/blob/references/all-sections.md) as your source, which has the correct reference IDs as well as templated values. But I'd also recommend looking into options that apply style to the PDF / HTML and don't require latex.

**Comment by evancofer** [comment]
I fiddled around with this a bit this morning. Using LaTeX I produced the following result:
[deep-review.pdf](https://github.com/greenelab/deep-review/files/1033672/deep-review.pdf)

I am currently searching for a LaTeX-free (e.g., HTML-based) solution.
