### ISSUE TITLE
Retrosynthetic reaction prediction using neural sequence-to-sequence models

### ISSUE THREAD

**Issue by agitter** [greenelab/deep-review#531]
https://arxiv.org/abs/1706.01643

> We describe a fully data driven model that learns to perform a retrosynthetic reaction prediction task, which is treated as a sequence-to-sequence mapping problem. The end-to-end trained model has an encoder-decoder architecture that consists of two recurrent neural networks, which has previously shown great success in solving other sequence-to-sequence prediction tasks such as machine translation. The model is trained on 50,000 experimental reaction examples from the United States patent literature, which span 10 broad reaction types that are commonly used by medicinal chemists. We find that our model performs comparably with a rule-based expert system baseline model, and also overcomes certain limitations associated with rule-based expert systems and with any machine learning approach that contains a rule-based expert system component. Our model provides an important first step towards solving the challenging problem of computational retrosynthetic analysis.

**Comment by mrwns** [comment]
I think chemical synthesis planning might be only indirectly relevant to the review. I think we even dropped the a chemical reaction section, right?

On the other hand, if we would include it, we could also add some of my recent publications... 

https://openreview.net/forum?id=SJ5JPtg_x&noteId=SJ5JPtg_x
http://onlinelibrary.wiley.com/doi/10.1002/chem.201605499/full

**Comment by agitter** [comment]
@mrwns I agree that it is probably not directly relevant, so I'll close the issue.  I'm personally interested in the topic though, so thanks for sharing both of your papers.
