### ISSUE TITLE
Deep learning: from chemoinformatics to precision medicine

### ISSUE THREAD

**Issue by alxndrkalinin** [greenelab/deep-review#557]
https://doi.org/10.1007/s40005-017-0332-x

> Deep learning is a new machine learning paradigm that focuses on learning with deep hierarchical models of data. Chemoinformatics has been defined as the mixing of chemical information resources to transform into knowledge for the intended purpose of making better and faster decisions in the area of drug lead identification and optimization. Precision medicine includes disease prevention and treatment strategies that consider individual variability in healthcare. Researchers are now focusing on the convergence of genomics, epigenomics, metabolomics, informatics, and imaging, along with other technologies such as data mining, deep learning, and big data methodology; disciplines that are rapidly expanding the scope of precision medicine. Drug and diagnostic developers, physicians, health systems, and patients share interests in precision medicine. In this review, we provide an overview of recent studies on the application of the deep learning method in the pharmaceuticals and precision medicine fields. We briefly review the fields related to the history of deep learning, chemoinformatics, drug development, model based medicine, electronic healthcare records, wearable sensors, drug response variability, and precision medicine.

I personally didn't like this article, I think it's very superficial, but decided to add anyway since we're sort of collecting related resources here, maybe someone will get something useful out of it.

**Comment by agitter** [comment]
It's good to open issues for papers like this so that we can discuss them and actively decide whether to include or exclude them.  I agree with your assessment.  I'll close the issue to indicate that we don't plan to add this to our review.  Anyone should still feel free to add further comments though.

**Comment by alxndrkalinin** [comment]
@agitter At this point issues in this repo became probably the biggest collection of DL bio applications out there, outgrowing other ones like awesome-deepbio. Would be interesting to think about sustainable ways to keep it expanding.

**Comment by agitter** [comment]
@alxndrkalinin Exactly!  That's why I keep posting papers here.  It helps me track the literature and opens it for discussion if anyone else watching finds a paper interesting.

I would like to think about a longer term strategy to sustain this effort.  I imagine enthusiasm will drop once the journal version of the review is finalized.  But because we have been using this as an experiment in publication, we should think about to keep this active (cc @cgreene).

**Comment by cgreene** [comment]
I agree with both of you. I'm not sure how to design a system that keeps this going. Maybe if we tweet about the ongoing discussions it will draw people in & make clear that it's still alive.

**Comment by agapow** [comment]
It's bloody useful, thanks guys. Can't help but think that github issues are perhaps not the best venue for it: I appreciate the alerts but they're drowning out my other alerts. Move it to the github wiki or pages?

**Comment by agitter** [comment]
@agapow That could be a good solution.  In the short term, I plan to add some of these papers from the recent issues in version 2 of our review, so I'll continue using issues for that.  Once the journal version of the paper is finished, I'm open to switching to another system.

**Comment by agapow** [comment]
It might need some thought about what's the necessary features are of any paper list:

- easily add items to list
- visitors can easily see what's new
- ability to comment upon them?

**Comment by cgreene** [comment]
I'd like to see something that has some level of archiving - and ideally even permanence/citability. Github doesn't help with this but it would be in the ideal system.

**Comment by cgreene** [comment]
Tagging @freeman-lab since this may be something he has also considered.

**Comment by akundaje** [comment]
One could create a bot that scrapes twitter feeds, arxiv and biorxiv feeds
etc to find relevant content. Mendeley, citeUlike, zotero could be good
ways to easily arxiv the references. Some of these like Mendeley have
public groups that folks can join and tag/comment etc. Also makes it easy
to directly convert to whatever bib format you want.
