### ISSUE TITLE
How to create a table

### ISSUE THREAD

**Issue by yfpeng** [greenelab/deep-review#558]
I am writing a subsection of deep learning for biomedical text mining. I need to add a table but I am not sure if our script supports it because tables aren't part of the core Markdown spec, but they are part of GFM.

**Comment by agitter** [comment]
I tested the [example GFM table from this guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables) and it worked in the HTML and PDF outputs:
![image](https://user-images.githubusercontent.com/3532898/27692441-4fcf85be-5cac-11e7-81e8-c97336d71a25.png)
![image](https://user-images.githubusercontent.com/3532898/27692451-5650634a-5cac-11e7-80e1-673350596200.png)

You can try it yourself before making a pull request by creating the [conda environment ](https://github.com/greenelab/deep-review/tree/master/build) and running the build script.  It's easy to set up if you have Anaconda installed.

The bigger question for @dhimmel (and maybe me) is how we want to handle table numbering, and more broadly how general the build process should be.  It should be possible to automate with Jinja2.  I imagine that in the markdown we could write `Table {{tables.network-architectures}}` and have it be automatically numbered as `Table 1` in the output.  We should move this discussion to another issue if we want to pursue it, but briefly we could have `references.py` call a function similar to `get_references_from_text` to get all table references.  Then we could number those references by their first appearance.  What gets a little more complicated is if we want to treat table references in the text differently from the actual tables, which would help keep the numbering stable regardless of table placement.  We'll need the same thing for figures if we add those (#354).

@yfpeng I suggest that you initially hard code the table number.

**Comment by dhimmel** [comment]
Good to know the markdown tables are working. FYI, http://www.tablesgenerator.com/markdown_tables is really helpful for creating markdown tables. If the table is large (many columns), consider enabling compact mode.

> I suggest that you initially hard code the table number.

Yes hardcode for now. The flexible solution will probably be along the lines of https://github.com/greenelab/deep-review/issues/354#issuecomment-306067719. We'll work on implementing that... don't worry about it for now.

**Comment by agitter** [comment]
Closed by #681.  `USAGE.md` now describes Manubot table support.

**Comment by dhimmel** [comment]
Yep. Just so we're all on the same page, tables and automatic table numbering are now supported.
