### ISSUE TITLE
Authors since initial submission

### ISSUE THREAD

**Issue by cgreene** [greenelab/deep-review#561]
I wanted to track this so that we don't lose contributors.

Tagging @avctrh 

New authors:
- [x] @austinvhuang (formerly @avctrh)
- [x] @SiminaB 
- [x] @michaelmhoffman 
- [x] @luzh2 
- [x] @lavenderca
- [x] @zietzm
  
Acknowledgement -> Author due to approval after v1 went out:
- [x] @swamidass

**Comment by agitter** [comment]
Perfect.  I'll add new authors in one batch once we are nearing a new version.

**Comment by agitter** [comment]
I added @SiminaB to the list above after merging #588.  That pull request alone may not meet ICMJE authorship criteria, but the discussion in #565 and incoming #566 do.

**Comment by agitter** [comment]
I added @michaelmhoffman after merging #620, noting that several other pull requests are still incoming.

**Comment by michaelmhoffman** [comment]
Thanks! Please don't forget to remove me from acknowledgments.

**Comment by evancofer** [comment]
This may be a silly question to ask on this pull request, but [how] do we plan on updating the author ordering? If we are still using the randomized hierarchies, are any transitions between them expected?

**Comment by agitter** [comment]
@evancofer It's a good idea to discuss this.  The algorithm I proposed in #369, [which is demoed here](https://github.com/agitter/deep-review/blob/author-order/authors/author_order_demo.ipynb), would:
- keep the random order for existing authors within each category
- randomly order the new authors within each category
- append the new authors to the end of the existing author list within each category
- concatenate the category-specific author lists

The main objectives were to continue to emphasize the categories instead of the specific order and also minimize changes.  I thought it would be confusing to have major permutations to the author list every time we add someone new.

**Comment by michaelmhoffman** [comment]
As a new author I think it is only fair that we get put at the end of whatever category we end up in.

**Comment by agitter** [comment]
Added @luzh2 above after merging #567

**Comment by agitter** [comment]
Added @lavenderca after merging #629

**Comment by agitter** [comment]
Added @zietzm after merging #638

**Comment by cgreene** [comment]
Talked with @swamidass at PSB. He contributed to the discussion of issues + writing on the first round (see Acknowledgements). He is now able to approve. I'm not sure what our procedure is this time around, but we should include him when we have things ready.

**Comment by swamidass** [comment]
Yes, I do approve.

**Comment by agitter** [comment]
@swamidass great, we'll add you in the next version.  I'll post instructions for adding yourself here.

@aaronsheldon you also contributed previously but didn't give final approval.  Do you want to review and approve this version to be added as an author?

@cgreene for the author-adding process, I'm thinking that we should once again have authors make pull requests to add their own information.  That ensures accuracy and gives a commit as record of approval.  I suggest that new authors add their information to a new file `content/new_authors.yaml` that I'll create using the format in [`content/metadata.yaml`](https://github.com/greenelab/deep-review/blob/master/content/metadata.yaml).  After the text and new authors stabilize (at the end of next week?), I'll run the randomized ordering and move the new authors to `metadata.yaml`.  Sound good?

**Comment by cgreene** [comment]
@agitter : plan sounds good to me. I agree with having the authors add their metadata via PR

**Comment by agitter** [comment]
@austinvhuang
@SiminaB
@michaelmhoffman
@luzh2
@lavenderca
@zietzm
@swamidass
we're ready for you to add your contact information to the author list.

Please submit a pull request to add your info to [`new-author-metadata.yaml`](https://github.com/greenelab/deep-review/blob/master/content/new-author-metadata.yaml), which will also indicate that you have read and approved the manuscript.  This list is unordered so you can add yourself to the bottom.  The `funders` entry is optional.  The placeholder entries provide example formatting; see [`metadata.yaml`](https://github.com/greenelab/deep-review/blob/master/content/metadata.yaml) for more examples.

Once all of the new authors are in `new-author-metadata.yaml`, I'll randomly order authors as described [above](https://github.com/greenelab/deep-review/issues/561#issuecomment-321537000) and insert you into `metadata.yaml`, which will add you to the manuscript.

**Comment by michaelmhoffman** [comment]
How do we add multiple affiliations? I am planning to add `Princess Margaret Cancer Centre, Toronto, ON, Canada; Department of Medical Biophysics, Toronto, ON, Canada; Department of Computer Science, Toronto, ON, Canada`.  I notice @agitter uses `affiliations: Department of Biostatistics and Medical Informatics, University of Wisconsin-Madison and Morgridge Institute for Research, Madison, WI`. Does that mean I should use the ambiguous `and` as a way of adding additional affiliations? Better to switch to semicolon?

**Comment by agitter** [comment]
My example is wrong.  You should use semi colon delimited as you suggested.

Better support for multiple affiliations is coming soon, but I'll update
your affiliation formatting when we update the manubot package version.

**Comment by agitter** [comment]
I'm reminding myself that when I move the new authors from `new-author-metadata.yaml` to `metadata.yaml` I need to manually update the funding section.  That part is no longer automatically generated.

**Comment by evancofer** [comment]
@agitter This is related to the affiliations question. How should we go about adding a new affiliation for an existing author? Should we manually add them to metadata.yaml and submit a PR?

**Comment by agitter** [comment]
@evancofer yes, authors should feel free to update any of their own information via pull request.  The affiliations in `metadata.yaml` are [now a list](https://github.com/greenelab/deep-review/blob/master/USAGE.md#manuscript-metadata), so you can either replace your existing affiliation or add an additional affiliation.

**Comment by austinvhuang** [comment]
Submitted my information as a PR, let me know if anything else is needed. Thanks!

**Comment by agitter** [comment]
All new authors have been added to `new-author-metadata.yaml`, and I don't anticipate any more authors for our next manuscript version.  @cgreene do you agree that I can insert them into the ordered author list after we merge #777?

I'll review the new authors' commits to place them in a contribution category and then update the ordered list as [described above](https://github.com/greenelab/deep-review/issues/561#issuecomment-321537000).

**Comment by cgreene** [comment]
I agree that we should put these authors into a new contribution category and perform the ordering as was done for the other categories earlier.

**Comment by agitter** [comment]
New contribution category or existing categories?  We can do either.  I initially planed to use our [existing categories](https://greenelab.github.io/deep-review/#author-contributions):
- Drafted multiple sub-sections along with extensive editing, pull request reviews, or discussion
- Drafted one or more sub-sections
- Revised specific sub-sections or supervised drafting one or more sub-sections
- Drafted sub-sections, edited the manuscript, reviewed pull requests, and coordinated co-authors

**Comment by cgreene** [comment]
Ahh - I would be fine with either, but putting new additions into a single category reduces shuffling of the author list.

**Comment by michaelmhoffman** [comment]
Should be no shuffling--I think what was discussed was putting in new authors in each of those categories *after* all previous authors in the category. (As a n00b I think it is far to put us after the authors for the first round within a category.) So up to four insertion points but no shuffling.

**Comment by cgreene** [comment]
@michaelmhoffman : sorry - misunderstood that then. 👍

**Comment by agitter** [comment]
I believe I have the same idea as @michaelmhoffman.  For hypothetical categories and authors:

Category1: Existing1, Existing2, New1, New2, New3
Category2: Existing3, Existing4, New4

Suppose we currently have: Existing2, Existing1, Existing3, Existing4.

The updated list could become: Existing2, Existing1, New2, New3, New1, Existing3, Existing4, New4.

**Comment by cgreene** [comment]
As a heads up, I need all of our authors to create an account at JRS-I so that I can associate it with the manuscript. Please post here when you've done it. Please use the email address listed in the metadata file.

Go to this address:
https://mc.manuscriptcentral.com/jrsi

Click "Create An Account" and associate your ORCID with the new account.

Post here that you have created your account.

**Comment by SiminaB** [comment]
Done.

**Comment by agitter** [comment]
New authors, please also note any conflicts of interest when you post here regarding your JRS-I account.

**Comment by lavenderca** [comment]
Done!  No conflicts of interest.

**Comment by michaelmhoffman** [comment]
Done. No COI.

**Comment by luzh2** [comment]
Done. No conflict of interest.

**Comment by cgreene** [comment]
@lavenderca : can you verify the email you used is the same as in: https://github.com/greenelab/deep-review/blob/master/content/metadata.yaml

If not, can you post it here or email it to me (greenescientist@gmail.com)?

Thanks!

**Comment by cgreene** [comment]
Ok - got all of the accounts added 👍

**Comment by lavenderca** [comment]
Ah!  My JRS-I account is associated with c.andrew.lavender@gmail.com.  Sorry about that!

**Comment by cgreene** [comment]
@lavenderca : got it!
