### ISSUE TITLE
642 features -> 62 features

### ISSUE THREAD

**Issue by aquaskyline** [greenelab/deep-review#562]
"Another method, still in its infancy, hand-developed 642 features for each candidate variant and fed these vectors into a fully connected deep neural network [@tag:Torracinta2016_deep_snp]"

Should be "62" features instead of "642" according to the reference.

**Comment by agitter** [comment]
Good catch!  Would you like to make the pull request to correct this, or shall I do it?

For reference, the paper states:
> These data were then converted to 62 features per site as illustrated in Figure 2 (see Methods for details about feature mapping).

**Comment by aquaskyline** [comment]
#564

**Comment by agitter** [comment]
#564 closes this issue
