### ISSUE TITLE
Protein-Protein Interaction subsection

### ISSUE THREAD

**Issue by zietzm** [greenelab/deep-review#575]
In reading through the Study section, I came across an area that I thought may be of interest but which was not yet covered by the review-- protein-protein interaction. Since classical machine learning approaches like SVM, random forest, etc. and things like Bayesian networks have been predominant, I think this section would be a potentially meaningful presentation of a good opportunity for deep learning. I found a few papers in which deep learning was applied to this topic and put them below.

1. [Sequence-based prediction of protein protein interaction using a deep-learning algorithm](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-017-1700-2)
2. [Deep Recurrent Neural Network for Protein Function Prediction from Sequence](https://doi.org/10.1101/103994)
3. [Structure-based prediction of protein–protein interactions on a genome-wide scale](http://www.nature.com/nature/journal/v490/n7421/full/nature11503.html)
4. [A novel method based on new adaptive LVQ neural network for predicting protein–protein interactions from protein sequences](https://doi.org/10.1016/j.jtbi.2013.07.001)

One aspect of PPI prediction that stands out is the diversity in features used between different studies. In fact, there was [a preprint](https://doi.org/10.1101/137257) just released whose purpose is to outline some of the various features for machine learning PPI prediction. This seems like a good indication in my mind that this field would be a prime target for further research that incorporates deep learning.

If this seems like a meaningful subsection to include, perhaps a suitable location would be just below the protein secondary and tertiary structure section. Right here, [greenelab/deep-review/sections/04_study.md](https://github.com/greenelab/deep-review/blob/master/sections/04_study.md#morphological-phenotypes) seems like it would be a logical location.

**Comment by agitter** [comment]
@zietzm protein-protein interactions are definitely an area of interest.  We had no reason to exclude this topic in the version, simply a lack of a contributor to research and write about it.  Would you be interested in leading this for the revised draft?

If so, I suggest that you create separate issues for the papers above so we can discuss them individually.  In addition to PPI prediction, this sub-section could also cover PPI network analysis.  As @mrwns pointed out in #543, PPI networks are also popular for graph representation learning and graph convolutions, topics I'm excited about.  #241 could also be reviewed to see if it fits in a new PPI sub-section.

**Comment by zietzm** [comment]
Thanks for the quick reply, and yes, I would be very interested in contributing! I will get on those things today.

**Comment by agitter** [comment]
Closed by #638
