### ISSUE TITLE
DeepPPI: Boosting Prediction of Protein–Protein Interactions with Deep Neural Networks

### ISSUE THREAD

**Issue by zietzm** [greenelab/deep-review#584]
https://doi.org/10.1021/acs.jcim.7b00028
>The complex language of eukaryotic gene expression remains incompletely understood. Despite the importance suggested by many proteins variants statistically associated with human disease, nearly all such variants have unknown mechanisms, for example, protein−protein interactions (PPIs). In this study, we address this challenge using a recent machine learning advance-deep neural networks (DNNs). We aim at improving the performance of PPIs prediction and propose a method called DeepPPI (Deep neural networks for Protein− Protein Interactions prediction), which employs deep neural networks to learn effectively the representations of proteins from common protein descriptors. The experimental results indicate that DeepPPI achieves superior performance on the test data set with an Accuracy of 92.50%, Precision of 94.38%, Recall of 90.56%, Specificity of 94.49%, Matthews Correlation Coefficient of 85.08% and Area Under the Curve of 97.43%, respectively. Extensive experiments show that DeepPPI can learn useful features of proteins pairs by a layer-wise abstraction, and thus achieves better prediction performance than existing methods. The source code of our approach can be available via http://ailab.ahu.edu. cn:8087/DeepPPI/index.html

The authors used an interesting approach by using parallel deep neural networks to extract features from both proteins separately, then combined the two into one NN. They showed this approach to be superior to a single, unified deep neural net. See below.

<img src="https://user-images.githubusercontent.com/7230303/28380360-050ac1cc-6c85-11e7-850d-23d1be04f77f.png" width="450">

**Comment by agitter** [comment]
Added in the `Protein-protein interactions` section
