### ISSUE TITLE
High-order neural networks and kernel methods for peptide-MHC binding prediction

### ISSUE THREAD

**Issue by zietzm** [greenelab/deep-review#585]
https://doi.org/10.1093/bioinformatics/btv371

>**Motivation**: Effective computational methods for peptide-protein binding prediction can greatly help clinical peptide vaccine search and design. However, previous computational methods fail to capture key nonlinear high-order dependencies between different amino acid positions. As a result, they often produce low-quality rankings of strong binding peptides. To solve this problem, we propose nonlinear high-order machine learning methods including high-order neural networks (HONNs) with possible deep extensions and high-order kernel support vector machines to predict major histocompatibility complex-peptide binding.
**Results**: The proposed high-order methods improve quality of binding predictions over other prediction methods. With the proposed methods, a significant gain of up to 25–40% is observed on the benchmark and reference peptide datasets and tasks. In addition, for the first time, our experiments show that pre-training with high-order semi-restricted Boltzmann machines significantly improves the performance of feed-forward HONNs. Moreover, our experiments show that the proposed shallow HONN outperform the popular pre-trained deep neural network on most tasks, which demonstrates the effectiveness of modelling high-order feature interactions for predicting major histocompatibility complex-peptide binding.

The authors applied both a DNN and a HONN in order to compare the two. See image below.

As it relates to PPI:
>In this article, we propose novel machine learning methods to study a specific type of peptide-protein interaction, i.e. the interaction between peptides and major histocompatibility complex class I (MHC I) proteins, although our methods can be readily applicable to other types of peptide-protein interactions.

<img src="https://user-images.githubusercontent.com/7230303/28382827-67df2060-6c8d-11e7-83d1-d50519236fcd.gif" width="300" border="20" />

**Comment by agitter** [comment]
This seems like a popular topic.  We have a [few related papers](https://github.com/greenelab/deep-review/issues?utf8=%E2%9C%93&q=MHC) logged, but I believe only one of them was cited in the first draft of the review.

**Comment by agitter** [comment]
Added in the `MHC-peptide binding` section
