### ISSUE TITLE
Vague: "Each layer performs feature construction for the layers before it."

### ISSUE THREAD

**Issue by michaelmhoffman** [greenelab/deep-review#593]
This sentence is not precise or easy to understand.

**Comment by michaelmhoffman** [comment]
Out of time.

**Comment by cgreene** [comment]
Maybe not ideal, but now says:

> The neural networks used for deep learning have multiple hidden layers. Each layer essentially performs feature construction for the layers before it. The training process used often allows layers deeper in the network to contribute to the refinement of earlier layers. For this reason, these algorithms can automatically engineer features that are suitable for many tasks and customize those features for one or more specific tasks.
