### ISSUE TITLE
Ranges should use an en dash, not a hyphen

### ISSUE THREAD

**Issue by michaelmhoffman** [greenelab/deep-review#610]

**Comment by michaelmhoffman** [comment]
@dhimmel To change a hyphen to an en dash do I just use the Unicode characters for en dash? Want to ensure this won't mess anything up.

**Comment by dhimmel** [comment]
You can use the unicode en dash `–` or do two hyphens `--` since we use pandoc's `--smart` option. Whichever you prefer.
