### ISSUE TITLE
Choosing a consistent nomenclature for auPRC and auROC

### ISSUE THREAD

**Issue by michaelmhoffman** [greenelab/deep-review#613]
The `C` in `ROC` stands for "characteristic", not "curve". I would remove the `C` from `auPRC` accordingly. (This is also how I've mostly seen it elsewhere.)

**Comment by dhimmel** [comment]
@michaelmhoffman what do you think about AUROC and AUPR versus auROC and auPR? The mixed capitalization seems arbitrary?

Would it be best to just use auROCc and auPRc (or the ALL CAPS variants of AUROCC and AUPRC)? Omitting curve seems imprecise.

Not that I care too much about these details, but I'd like to flesh them out for future use anyways.

**Comment by agitter** [comment]
My current favorite abbreviations are `AUCROC` and `AUCPR`.  Those are similar to what are used in the excellent [Davis and Goadrich paper](http://machinelearning.wustl.edu/mlpapers/paper_files/icml2006_DavisG06.pdf) except they use `AUC-ROC` and `AUC-PR`.  I'm okay with the hyphenated versions too.

**Comment by michaelmhoffman** [comment]
I'd prefer to not have the lowercase letters either. Mixed case abbreviations are an abomination.

Google Trends confirms that AUROC and AUPR are most common. I can see how AUCROC and AUCPR would make more sense. Subscript AUC_ROC or AUC_PR would also work. Hard no to auROCc from me :) and also dislike AUPRC.

https://trends.google.com/trends/explore?q=auroc,aucroc,auprc,aupr,aucpr

**Comment by dhimmel** [comment]
@michaelmhoffman great idea with the google trends. I expanded the view to a 5 year window (https://g.co/trends/fdwpG):

![aupr-auroc-trends](https://user-images.githubusercontent.com/1117703/30703945-1eae1c48-9ebf-11e7-8e74-227ba4d6da14.png)

Given their sustained dominance, I'm in favor of `AUROC` and `AUPR`.

**Comment by agitter** [comment]
I'll defer to the data.  `AUROC` and `AUPR` sound fine to me.
