### ISSUE TITLE
Cite `The Cancer Genome Atlas`

### ISSUE THREAD

**Issue by michaelmhoffman** [greenelab/deep-review#616]

**Comment by michaelmhoffman** [comment]
Can't figure out which paper to cite. Asked on Twitter: https://twitter.com/michaelhoffman/status/952959133921267713

**Comment by michaelmhoffman** [comment]
Since it is a reference to what's done in `@tag:WayGreene2017_tybalt`, we should probably cite the same thing they do, which is `@doi:10.1038/ng.2764`.

**Comment by agitter** [comment]
Closed by #783
