### ISSUE TITLE
Rework promoter/enhancer section a bit

### ISSUE THREAD

**Issue by michaelmhoffman** [greenelab/deep-review#621]
Work in progress in [promoter-enhancer](/michaelmhoffman/deep-review/tree/promoter-enhancer) branch of `michaelmhoffman/deep-review`.

- [x] write new intro
- [x] reorganize into new subsubsections
- [x] write new intro for `Promoters`
- [x] reduce `Promoters`
- [x] write new intro for `Enhancers`
- [x] reduce `Enhancers`
- [x] write new intro for `Promoter-enhancer interactions`
- [x] reduce `Promoter-enhancer interactions`
- [x] submit pull request

**Comment by agitter** [comment]
Will these changes introduce merge conflicts with any of #618, #619, #620?  In the worst case, you could help use resolve the merge conflicts before we merge the pull request.

**Comment by michaelmhoffman** [comment]
I don't think it should. But of course I'm happy to resolve anything in this branch against the master branch.

**Comment by agitter** [comment]
This spans multiple issues, but I'm noting here that I created the `manuscript` label for these and other issues that pertain to manuscript changes.  That will help us find and close them once they get mixed up with the issues tracking new papers.
