### ISSUE TITLE
Predicting protein–protein interactions from protein sequences by a stacked sparse autoencoder deep neural network

### ISSUE THREAD

**Issue by zietzm** [greenelab/deep-review#626]
https://doi.org/10.1039/C7MB00188F
 > Protein–protein interactions (PPIs) play an important role in most of the biological processes. How to correctly and efficiently detect protein interaction is a problem that is worth studying. Although high-throughput technologies provide the possibility to detect large-scale PPIs, these cannot be used to detect whole PPIs, and unreliable data may be generated. To solve this problem, in this study, a novel computational method was proposed to effectively predict the PPIs using the information of a protein sequence. The present method adopts Zernike moments to extract the protein sequence feature from a position specific scoring matrix (PSSM). Then, these extracted features were reconstructed using the stacked autoencoder. Finally, a novel probabilistic classification vector machine (PCVM) classifier was employed to predict the protein–protein interactions. When performed on the PPIs datasets of Yeast and H. pylori, the proposed method could achieve average accuracies of 96.60% and 91.19%, respectively. The promising result shows that the proposed method has a better ability to detect PPIs than other detection methods. The proposed method was also applied to predict PPIs on other species, and promising results were obtained. To evaluate the ability of our method, we compared it with the-state-of-the-art support vector machine (SVM) classifier for the Yeast dataset. The results obtained via multiple experiments prove that our method is powerful, efficient, feasible, and make a great contribution to proteomics research.

Used stacked sparse autoencoder as a middle step to reduce feature dimension and noisiness. Zernike moments used as initial features while novel (probabilistic classification) vector machine was used for prediction.

**Comment by agitter** [comment]
Added in the `Protein-protein interactions` section
