### ISSUE TITLE
Ways to provide more intuition

### ISSUE THREAD

**Issue by SiminaB** [greenelab/deep-review#630]
This is a general issue, related e.g. to https://github.com/greenelab/deep-review/issues/354 https://github.com/greenelab/deep-review/pull/566. I know this isn't meant to be a general thorough introduction to DL, but I'm wondering whether we should include things like the fact that a feedforward neural network with a single layer that uses the logistic function is equivalent to logistic regression etc. I think it could be worthwhile to add a few examples (could be within figures) to "open up the black box" a bit.

**Comment by agitter** [comment]
I think this could work well as a way to contrast logistic regression (a sigmoid output layer) on the original features versus learned features in a hidden layer.  A figure may best convey the idea.

**Comment by SiminaB** [comment]
I'm still thinking about what a good overview figure should convey... I did try to add a bit intuition in the Intro in https://github.com/greenelab/deep-review/pull/566

**Comment by agitter** [comment]
Proposing we close this.  The table, figure, and revised intro text help.
