### ISSUE TITLE
Acknowledgements since initial submission

### ISSUE THREAD

**Issue by agitter** [greenelab/deep-review#637]
Analogous to #561 for author changes, this issue will track acknowledgement changes for the next release.

Additions:
- @souravsingh
- _Pending_

Removals:
- @michaelmhoffman (move to author list)
- @swamidass (move to author list)

**Comment by agitter** [comment]
Adding @souravsingh for #705.  Thanks!

**Comment by cgreene** [comment]
See #751 . Didn't get the add, but I can quickly do that if you let me know if this text is useful:
"We would like to thank GitHub user souravsingh for repairing a wrongly formatted reference."

**Comment by agitter** [comment]
@cgreene now that we're close to a new version, I think it makes sense to add all of the new acknowledgements in #751 so we don't forget.  We have a few to add so we may want to make it more general and say something like `for correcting typos, formatting, and references.`

I went through our 41 contributors, and we should acknowledge @souravsingh, @rgieseke, and @aquaskyline.  All of the others are current or pending authors, contributed to manubot (see below), or are already acknowledged.

@souravsingh is it okay with you if we acknowledge you as `Sourav Singh` instead of by your GitHub username?

@rgieseke can we acknowledge you as `Robert Gieseke` for [these typo, licensing, and anchors contributions](https://github.com/greenelab/deep-review/commits?author=rgieseke)?

@aquaskyline can we acknowledge you as `Ruibang Luo` for [this typo fix](https://github.com/greenelab/deep-review/commits?author=aquaskyline)?

**vsmalladi**, **slochower**, and **petebachant** authored commits that are included in our commit log because of the manubot rootstock merge.  I plan to credit those in the eventual manubot paper instead of deep review.  Does that sound best to you @dhimmel?

**Comment by aquaskyline** [comment]
Yes.

**Comment by rgieseke** [comment]
Yes, thank you!

**Comment by dhimmel** [comment]
> vsmalladi, slochower, and petebachant authored commits that are included in our commit log because of the manubot rootstock merge. I plan to credit those in the eventual manubot paper instead of deep review. Does that sound best to you @dhimmel?

Yes.

**Comment by agitter** [comment]
Closed by #751
