### ISSUE TITLE
Extracting a Biologically Relevant Latent Space from Cancer Transcriptomes with Variational Autoencoders

### ISSUE THREAD

**Issue by agitter** [greenelab/deep-review#639]
https://doi.org/10.1101/174474

> The Cancer Genome Atlas (TCGA) has profiled over 10,000 tumors across 33 different cancer-types for many genomic features, including gene expression levels. Gene expression measurements capture substantial information about the state of each tumor. Certain classes of deep neural network models are capable of learning a meaningful latent space. Such a latent space could be used to explore and generate hypothetical gene expression profiles under various types of molecular and genetic perturbation. For example, one might wish to use such a model to predict a tumor's response to specific therapies or to characterize complex gene expression activations existing in differential proportions in different tumors. Variational autoencoders (VAEs) are a deep neural network approach capable of generating meaningful latent spaces for image and text data. In this work, we sought to determine the extent to which a VAE can be trained to model cancer gene expression, and whether or not such a VAE would capture biologically-relevant features. In the following report, we introduce a VAE trained on TCGA pan-cancer RNA-seq data, identify specific patterns in the VAE encoded features, and discuss potential merits of the approach. We name our method "Tybalt" after an instigative, cat-like character who sets a cascading chain of events in motion in Shakespeare's "Romeo and Juliet." From a systems biology perspective, Tybalt could one day aid in cancer stratification or predict specific activated expression patterns that would result from genetic changes or treatment effects.

@gwaygenomics or @cgreene want to add this?

See also https://github.com/greenelab/tybalt

**Comment by cgreene** [comment]
We could add a brief mention. I think the major points of the paper are basically:
* This is possible.
* It may have some nice properties.

It's pretty early-stage work akin to what #6 was for DAs in this space. I'm excited about the potential of deep methods that learn a meaningful latent space, but I don't want to oversell this at this point.

**Comment by agitter** [comment]
Added to the `Latent space manipulation` section
