### ISSUE TITLE
Predicting Cardiovascular Risk Factors from Retinal Fundus Photographs using Deep Learning

### ISSUE THREAD

**Issue by agitter** [greenelab/deep-review#646]
https://arxiv.org/abs/1708.09843v1

> Traditionally, medical discoveries are made by observing associations and then designing experiments to test these hypotheses. However, observing and quantifying associations in images can be difficult because of the wide variety of features, patterns, colors, values, shapes in real data. In this paper, we use deep learning, a machine learning technique that learns its own features, to discover new knowledge from retinal fundus images. Using models trained on data from 284,335 patients, and validated on two independent datasets of 12,026 and 999 patients, we predict cardiovascular risk factors not previously thought to be present or quantifiable in retinal images, such as such as age (within 3.26 years), gender (0.97 AUC), smoking status (0.71 AUC), HbA1c (within 1.39%), systolic blood pressure (within 11.23mmHg) as well as major adverse cardiac events (0.70 AUC). We further show that our models used distinct aspects of the anatomy to generate each prediction, such as the optic disc or blood vessels, opening avenues of further research.

**Comment by Omikar243** [comment]
Hi sir, Could you please upload the dataset you used in this research?

**Comment by agitter** [comment]
Hi @Omikar243, you'll have to contact the authors of this study. This issue was to discuss the manuscript as part of a review article about deep learning in biomedicine. Our team was not involved in the research.

**Comment by Omikar243** [comment]
I'm sorry but can you give me their contact info or any means through which I can contact them?

**Comment by agitter** [comment]
I don't know how to contact them. I suggest checking their preprint. If there isn't contact information there, my general advice for finding contact information for a researcher is to search Google Scholar for recent papers they have published in hopes one of them has current contact information. However, that's outside the scope of this issue.
