### ISSUE TITLE
ChestX-ray8 data

### ISSUE THREAD

**Issue by agitter** [greenelab/deep-review#666]
In #492 we removed the link for the ChestX-ray8 imaging dataset because we were unable to access it.  The conference paper has now appeared, and there is a link to the data https://nihcc.app.box.com/v/ChestXray-NIHCC.  We could add this back to the manuscript.

**Comment by yfpeng** [comment]
Yes. It tooks us a couple of more months to remove all personally identifiable information before release. The link is permanent.

**Comment by agitter** [comment]
@yfpeng thanks for adding the new URL.  The metadata couldn't be extracted automatically from that URL so the reference shows up as

> 73. In press. CXR8 | Powered By Box. See https://nihcc.app.box.com/v/ChestXray-NIHCC.

Can you please update `references/manual-references.json` with a CSL JSON entry for this URL?  You can search `"type": "webpage"` for other examples in that file and see the [Manubot rootstock usage](https://github.com/greenelab/manubot-rootstock/blob/master/USAGE.md#reference-metadata) for more details.
