### ISSUE TITLE
SD-MSAEs: Promoter recognition in human genome based on deep feature extraction

### ISSUE THREAD

**Issue by agitter** [greenelab/deep-review#67]
http://doi.org/10.1016/j.jbi.2016.03.018

**Comment by gwaygenomics** [comment]
I quickly skimmed this paper - it is somewhat difficult to read. I am not sure it is a paper we will want to highlight

**Comment by agitter** [comment]
I created the issue, but it's fine with me if we skip this one.  In general, I've created issues for papers that could be relevant, but I don't necessarily endorse them.  For this paper in particular, I don't see anything critical we need to discuss.  It initially caught my eye because it applies autoencoders to a different type of biological data (sequence).

Because we have a long list of papers, should we close or label issues once we agree we won't include them?

**Comment by cgreene** [comment]
I would say close if we are sure that we won't include.

**Comment by agitter** [comment]
@gwaygenomics do you think we should close this?  I agree with the logic in #66.  Our goal isn't to enumerate all of the biological problems that autoencoders have been applied to, in which case I suggest we close this issue.

**Comment by gwaygenomics** [comment]
@agitter agreed
