### ISSUE TITLE
Could you please update me the current status of journal submission

### ISSUE THREAD

**Issue by yfpeng** [greenelab/deep-review#670]
Thanks in advance!

**Comment by agitter** [comment]
@cgreene still hasn't heard from the journal.  Enough time has passed that we debated contacting the editor to ask about the review status, but we elected not to do that yet.  One main motivation is that the two of us haven't had enough time to manage pull requests on our own over the past months.  We'll need help from other contributions to make _and review_ pull requests during revisions.

If others are ready to spend time working on revisions, we could ask for a status update.

**Comment by cgreene** [comment]
I logged in to make sure I hadn't missed an email. I can confirm the status is still awaiting reviewer scores.

**Comment by agapow** [comment]
Pleased to help with PRs. I think lots of people like myself have let our attention drop after submission due to the usual pressures of academia. Any good way to signal everyone back to the thread?

**Comment by agitter** [comment]
> let our attention drop after submission due to the usual pressures of academia

That describes me as well.  It may be most efficient to rally contributors and review pull requests after we receive reviews from the journal.  If the journal instructs us to cut 30% of our text, we won't be able to accept large new sections as submitted.

Creating a new issue with revision TODOs and tagging all paper contributors would be a good way to get everyone's attention when we're ready.

**Comment by dhimmel** [comment]
Reviews are in. See https://github.com/greenelab/deep-review/issues/678
