### ISSUE TITLE
Upgrading repo to track manubot-rootstock

### ISSUE THREAD

**Issue by dhimmel** [greenelab/deep-review#680]
The Deep Review predates the Manubot (the CI-based system we use to process the manuscript). In fact, [`greenelab/manubot-rootstock`](https://github.com/greenelab/manubot-rootstock) (a template GitHub repo for Manubot instances) and [`greenelab/manubot`](https://github.com/greenelab/manubot) (a python package for processing the manuscript) were both derived from the code from Deep Review. In other words, Deep Review gave birth to these projects.

However, the Manubot has now diverged considerably from the codebase and architecture present in this repository. The manuscript processing code in this repository has not been receiving any rootstock updates. As time goes on, the reconciliation of the codebases becomes more difficult. However, once synchronized, incremental updates should generally be straightforward.

In https://github.com/greenelab/deep-review/issues/678#issuecomment-341539497, I proposed merging in the latest manubot-rootstock. @agitter [replied](https://github.com/greenelab/deep-review/issues/678#issuecomment-341612892):

> @dhimmel maybe we should open a new issue to preview and discuss how much would be involved in the merge. I'm hesitant to create a lot of new work when the current version of deep review is running smoothly even if it lacks some (important) features.

The merge certainly could be difficult. I'm happy to take on the task with a focus on minimizing disruption to open pull requests. The main benefits I see to the upgrade are:

+ getting new Manubot features including improved CI build feedback, formatting, and architecture
+ providing users with an up-to-date Manubot experience. The Deep Review is the Manubot instance with the greatest number of contributors. So we should strive to give users the cutting edge Manubot experience.
+ this repository has some customizations such as a non-standard (in terms of Manubot) authorship list. I'm interesting in seeing how the current Manubot architecture accommodates these needs. In other words, the Deep Review can provide important feedback for how to improve Manubot... but only if it's actually running Manubot.

Anyways, I'll attempt a merge and PR, so we can see exactly what the upgrade will entail. Most likely we will have to remove the current author scripts and re-engineer them, which I am willing to do.

**Comment by agitter** [comment]
Good luck with the merge.  This will also add proper figure and table support, which we'll need for the revisions.

How much has changed from the author perspective?  The citation syntax is slightly different now.  Is that it?  We already asked all of the contributors learn one custom writing platform so I want to be conscious of how many new requirements we impose.

**Comment by dhimmel** [comment]
> How much has changed from the author perspective?

https://github.com/greenelab/deep-review/pull/681/commits/12ce17cdfa572cca61f16457fa99e705826719c9 contains the changes to the manuscript body. Really the only change that users will need to be aware of is to semicolon separate references. Once we see the effect on open PRs, I can post a message on every open PR regarding if any upgrade steps are needed and offer help if neccessary.

**Comment by dhimmel** [comment]
I'd also like to start phasing in "one line per sentence" rather than word wrap. I think the best way to do this would be to operate on sections without any open PRs. And then when editing sections, we can encourage one line per sentence.

**Comment by agitter** [comment]
> I'd also like to start phasing in "one line per sentence" rather than word wrap

We had an issue about that and there was broad consensus that we should convert.  Someone had a simple script to implement the change.  I don't have the issue number accessible right now though.

**Comment by dhimmel** [comment]
> We had an issue about that

https://github.com/greenelab/deep-review/issues/624 proposed by @michaelmhoffman. @michaelmhoffman if you are interested in doing this, then you can take the lead (wait for #681 to be merged). Otherwise I can.

**Comment by michaelmhoffman** [comment]
I would like to punt to @evancofer who already wrote a script to do this.
