### ISSUE TITLE
Emdash vs endash

### ISSUE THREAD

**Issue by SiminaB** [greenelab/deep-review#695]
Should we use -- or - ? Raised by @agapow here: https://github.com/greenelab/deep-review/pull/566

**Comment by agitter** [comment]
#592 (cc @michaelmhoffman) suggested converting double en dash (`--`) to em dash (`—`).  I support that.  We can follow the [Wikipedia guidelines](https://en.wikipedia.org/wiki/Dash).

Before the initial submission we standardized everything to `--`, so we should be able to covert the existing punctuation fairly easily after merging outstanding pull requests.

I'm closing this, but we can continue discussing in #592 if needed.

**Comment by SiminaB** [comment]
Thanks! Sorry I didn't see that.

**Comment by agitter** [comment]
@SiminaB It's understandable, there are a lot of issues!  It's easy to miss old ones.
