### ISSUE TITLE
What figure formats are acceptable?

### ISSUE THREAD

**Issue by yfpeng** [greenelab/deep-review#697]
Please advise which figure formats are acceptable by the journal. It will be helpful to choose the right drawing tool(s).

**Comment by agitter** [comment]
@dhimmel My quick glance at the pandoc and pandoc-fignos didn't provide an answer.  Do you know?

**Comment by dhimmel** [comment]
I would recommend exporting a raster and vector format. For the raster format, use PNG unless there's pervasive color variation (like in a photograph), in which case use JPG. For vectors, try SVG first. If SVG fails or is not available, use PDF.

The Manubot output formats will work with PNG, JPG, and most SVGs.

**Comment by yfpeng** [comment]
Thanks. I am also asking for the journal author instructions. Sometimes, the journal has special requirements for figure formats.

**Comment by SiminaB** [comment]
It looks like they allow most file formats https://royalsociety.org/journals/authors/author-guidelines/ 

> All figures and tables should be numbered and referred to in the text by their number.
> 
> Figures should be uploaded as separate files and should include labels which are referred to in the captions. The following file formats are accepted:
> 
> TIFF
> Adobe Photoshop
> JPEG
> PowerPoint, Excel or Word if the figure was created using 1 of these packages
> Postscript (PS, EPS or PDF)
> Adobe Illustrator
> TeX/LaTeX-coded figures should be converted to postscript format (PS, EPS or PDF).
> 
> Colour figures are welcomed. All figures will be published in colour online (the version of record), but will be reproduced in black and white in the print version of the journal by default. If you feel that print colour is essential for any of your figures, please list the relevant figure numbers on submission of your article. Please note that, because of the high cost of colour printing, the final decision on colour usage is made at the discretion of the Editor.

**Comment by yfpeng** [comment]
Thank you! It looks like PGN and SVG are not acceptable.

**Comment by SiminaB** [comment]
They're not listed, but you can probably just convert to PDF.
