### ISSUE TITLE
Update bioRxiv and arXiv citations as needed

### ISSUE THREAD

**Issue by agitter** [greenelab/deep-review#699]
Before resubmitting we should update preprint references for manuscripts that have now been published.  The Manubot build reports arXiv manuscripts that are now associated with a doi.  We'll need to check bioRxiv manually.

**Comment by agitter** [comment]
I'm extending this to note that these references need to be added to `manual-references.json` because of problems with special characters:
- https://doi.org/10.3389/fgene.2014.00342
- https://doi.org/10.1534/g3.116.033654
- https://doi.org/10.2337/diabetes.54.suppl_2.S68

**Comment by souravsingh** [comment]
https://doi.org/10.3389/fgene.2014.00342 is now added to the manual references. I can now work on the rest of the references.

**Comment by agitter** [comment]
Edited to add Maaten2008_tsne (http://www.jmlr.org/papers/v9/vandermaaten08a.html) from #648.

**Comment by agitter** [comment]
@dhimmel I noticed the greycite is back up.  http://www.jmlr.org/papers/v9/vandermaaten08a.html is now processed automatically, as was the new URL from #774.

**Comment by agitter** [comment]
@dhimmel when I built deep review locally I saw a message about published arXiv papers that doesn't appear in the Travis build:
```
## WARNING
arXiv article 1704.01155 published at https://doi.org/10.14722/ndss.2018.23198
## WARNING
arXiv article 1704.03296 published at https://doi.org/10.1109/ICCV.2017.371 â€” Proceedings of the 2017 IEEE International Conference on Computer
  Vision (ICCV)
```

That doesn't seem like a problem, but I hadn't thought about this possibility before.  It may be a good practice to periodically clear the cache during a local build to check for arXiv updates.

**Comment by agitter** [comment]
We have be having a problem parsing http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.231.3442
https://github.com/greenelab/deep-review/blob/16809c82043f9f2540857afd58dc51215eba732e/citations.tsv#L519

I'm going to switch to a tag to see if that helps.

**Comment by agitter** [comment]
Closing this issue.  I corrected all of the reference errors I found and don't plan to manually review all bioRxiv and arXiv citations to see if they have been published.
