### ISSUE TITLE
Maximum entropy methods for extracting the learned features of deep neural networks

### ISSUE THREAD

**Issue by michaelmhoffman** [greenelab/deep-review#704]
> New architectures of multilayer artificial neural networks and new methods for training them are rapidly revolutionizing the application of machine learning in diverse fields, including business, social science, physical sciences, and biology. Interpreting deep neural networks, however, currently remains elusive, and a critical challenge lies in understanding which meaningful features a network is actually learning. We present a general method for interpreting deep neural networks and extracting network-learned features from input data. We describe our algorithm in the context of biological sequence analysis. Our approach, based on ideas from statistical physics, samples from the maximum entropy distribution over possible sequences, anchored at an input sequence and subject to constraints implied by the empirical function learned by a network. Using our framework, we demonstrate that local transcription factor binding motifs can be identified from a network trained on ChIP-seq data and that nucleosome positioning signals are indeed learned by a network trained on chemical cleavage nucleosome maps. Imposing a further constraint on the maximum entropy distribution also allows us to probe whether a network is learning global sequence features, such as the high GC content in nucleosome-rich regions. This work thus provides valuable mathematical tools for interpreting and extracting learned features from feed-forward neural networks.

https://doi.org/10.1371/journal.pcbi.1005836

**Comment by agitter** [comment]
Closing and merging with the preprint issue #240

**Comment by michaelmhoffman** [comment]
My bad for not doing a text search. I saw how new this paper was and only checked the recent issues filed since the publication date.

Thanks for fixing!
