### ISSUE TITLE
Mitosis Detection in Breast Cancer Histology Images with Deep Neural Networks

### ISSUE THREAD

**Issue by agitter** [greenelab/deep-review#71]
http://doi.org/10.1007/978-3-642-40763-5_51

Of the **many** papers using deep learning for histology applications, this one is fairly well-cited.  I don't know this area well, but it could serve as a starting point to find relevant imaging work.  They appear to have done well on this 2012 challenge http://doi.org/10.4103/2153-3539.112693

**Comment by brettbj** [comment]
I presented this at a Greenelab journal club way back actually, we should also note this: http://sagebase.org/in-the-news/digital-mammography-dream-challenge/ going on now

**Comment by agitter** [comment]
@brettbj I haven't read this yet.  Do you think we should include it in the review?

Nice catch with the DREAM challenge.  I hadn't noticed that one.
