### ISSUE TITLE
deepNF: Deep network fusion for protein function prediction

### ISSUE THREAD

**Issue by agitter** [greenelab/deep-review#715]
https://doi.org/10.1101/223339 (https://www.biorxiv.org/content/early/2017/11/22/223339)

> The prevalence of high-throughput experimental methods has resulted in an abundance of large-scale molecular and functional interaction networks. The connectivity of these networks provide a rich source of information for inferring functional annotations for genes and proteins. An important challenge has been to develop methods for combining these heterogeneous networks to extract useful protein feature representations for function prediction. Most of the existing approaches for network integration use shallow models that cannot capture complex and highly-nonlinear network structures. Thus, we propose deepNF, a network fusion method based on Multimodal Deep Autoencoders to extract high-level features of proteins from multiple heterogeneous interaction networks. We apply this method to combine STRING networks to construct a common low-dimensional representation containing high-level protein features. We use separate layers for different network types in the early stages of the multimodal autoencoder, later connecting all the layers into a single bottleneck layer from which we extract features to predict protein function. We compare the cross-validation and temporal holdout predictive performance of our method with state-of-the-art methods, including the recently proposed method Mashup. Our results show that our method outperforms previous methods for both human and yeast STRING networks. We also show substantial improvement in the performance of our method in predicting GO terms of varying type and specificity.

@VGligorijevic The linked repository https://github.com/VGligorijevic/deepNF gives a 404.  Did you intend to make it public? (*edit: repository is now public*)

@zietzm this looks relevant for #689

**Comment by jlaw9** [comment]
Found this issue googling for the deepNF repository. It's accessible now.

**Comment by agitter** [comment]
Thanks, I edited the original post to note that
