### ISSUE TITLE
Table width

### ISSUE THREAD

**Issue by agitter** [greenelab/deep-review#719]
@dhimmel Table 1 renders in a very narrow format when I view the HTML manuscript:
![image](https://user-images.githubusercontent.com/3532898/34053545-d64faec4-e18c-11e7-82d0-7241795473cd.png)

Do you know how to control the table width or why it is rendering like this?

**Comment by dhimmel** [comment]
From https://pandoc.org/MANUAL.html#tables

> If a pipe table contains a row whose printable content is wider than the column width (see --columns), then the cell contents will wrap, with the relative cell widths determined by the widths of the separator lines. (In this case, the table will take up the full text width.)

Anyways I'm not sure why "In this case, the table will take up the full text width" was not triggered.

Fixed in #720 by making the separator line larger.
