### ISSUE TITLE
How to fix my git repository which is ahead of greenlab:master

### ISSUE THREAD

**Issue by michaelmhoffman** [greenelab/deep-review#780]
Hi, I have been working off [michaelmhoffman/deep-review](https://github.com/michaelmhoffman/deep-review/). I added my affiliation and submitted a pull request, but I'm not sure if this commit (67ce7d352154323b6e071bd99d64c857ea888680) was accepted into upstream. My author information was added, with a slightly different affiliation format (by @agitter or @dhimmel?) . Trying to pull from upstream I got a conflict in my own repository, which I resolved in favor of upstream. Now "This branch is 2 commits ahead of greenelab:master."

How do I fix this? I find some suggestions online which seem like they might be destructive. Concerned that destroying that old commit might mess up the old pull request that references it.

**Comment by dhimmel** [comment]
> Concerned that destroying that old commit might mess up the old pull request that references it.

The old pull request has been merged... so no need to worry about this.

> I find some suggestions online which seem like they might be destructive

Yes. You'll want to be destructive and reset your `master` branch to the `upsream:master`:

```
git checkout master
git fetch upstream
git reset --hard upstream/master
git push origin master --force
```

In the future, don't commit directly to your master branch. Instead, make a new branch for each pull request. Then you'll avoid this issue. More about the suggested workflow [here](https://github.com/cognoma/cognoma/blob/master/CONTRIBUTING.md#contribution-workflow).

**Comment by michaelmhoffman** [comment]
Thanks @dhimmel, fixed, and will try that workflow from now on.
