### ISSUE TITLE
Semantic newlines not used correctly in some multi-reference lists or after `e.g.`

### ISSUE THREAD

**Issue by michaelmhoffman** [greenelab/deep-review#791]
`;` and `.` appear to have been triggers for a hard newline even when the `;` is in the middle of a reference list, or the `.` is part of e.g. `e.g.`.

**Comment by dhimmel** [comment]
It's possible that I missed some things in https://github.com/greenelab/deep-review/pull/730. While it won't effect the output, we'll appreciate any PRs to address these issues.

The best time to do this kind of thing is when few PRs are open that are also changing those lines.

**Comment by michaelmhoffman** [comment]
Yeah, I considered making a PR for it but that seemed stupid given all the open PRs.

**Comment by dhimmel** [comment]
No PRs currently open, so now would be the time if you have some small things you want to touch up.

**Comment by michaelmhoffman** [comment]
@dhimmel Could I request an expedited review due to the nature of this patch?
