### ISSUE TITLE
Issues #592-616

### ISSUE THREAD

**Issue by michaelmhoffman** [greenelab/deep-review#793]
I have reviewed all of these. For each one I either (a) created a pull request addressing it, (b) tagged an author to fix, or (c) wrote "Out of time".

**Comment by agitter** [comment]
Thanks!  I'll work on the pull requests today and tomorrow.

Can we close this and work on the individual pull requests from here?

**Comment by michaelmhoffman** [comment]
Not a problem. Just wanted to move the meta-discussion out of #609.
