### ISSUE TITLE
Manuscript diff for reviewers

### ISSUE THREAD

**Issue by agitter** [greenelab/deep-review#798]
@dhimmel there are several options in greenelab/manubot-rootstock#54 for creating a manuscript diff to submit to the journal along with the revised manuscript.  Do you have a recommendation for deep review?

**Comment by agitter** [comment]
I tried draftable with our current PDF and https://github.com/greenelab/deep-review/blob/55e779bc418f18e565b3598cc324fa15eeef383b/deep-review.pdf, which is approximately the version we submitted originally.

The results: https://draftable.com/compare/rtWcYEXlwupA

It does great for some sections, but others are marked as entirely new.

**Comment by dhimmel** [comment]
In the past, I've used the Word of Microsoft to compare and track changes between the two DOCX files. I think all of the methods will struggle with translocations. We could also try latexdiff. @agitter what do you think?

**Comment by agitter** [comment]
Will we be able to build a DOCX version of the original submission?  I wasn't sure whether we'd have to modify the pre-manubot build system to do that.

If it is easy to compare two DOCX versions, let's try that to see how it compares to draftable.  If that takes a lot of effort, I'm okay using draftable as a backup plan.

**Comment by agitter** [comment]
Word's diff is better than draftable's.  `gh-pages` commit 005cc002765cb85a9441b57c5f87bd7960508c62 is based on version fb6f113a21059f342fb1f571713d7e3cd01cbeb2, which we tagged as [version v0.9-preprint](https://github.com/greenelab/deep-review/releases/tag/v0.9-preprint).  I used htmlpreview to view that version of the [HTML manuscript](http://htmlpreview.github.io/?https://github.com/greenelab/deep-review/blob/005cc002765cb85a9441b57c5f87bd7960508c62/index.html) then copy/pasted it into a DOCX file:
[deep-review-v0.9-preprint.docx](https://github.com/greenelab/deep-review/files/1643882/deep-review-v0.9-preprint.docx)

I then copy/pasted the current HTML version into another DOCX and compared versions.  The diff looks good to me:
[deep-review-diff.docx](https://github.com/greenelab/deep-review/files/1643885/deep-review-diff.docx)

@cgreene once we finalize the manuscript, I'll do this once more so we can submit the DOCX with tracked changes along with the new PDF.

**Comment by agitter** [comment]
Here is the diff between [version v0.9-preprint](https://github.com/greenelab/deep-review/releases/tag/v0.9-preprint) and b3b57d37c4accabc2e15fd1d3f320a52ce25ed8b:
[deep-review-diff.docx](https://github.com/greenelab/deep-review/files/1645294/deep-review-diff.docx)

**Comment by agitter** [comment]
Closed per [journal resubmission](https://twitter.com/GreeneScientist/status/954335257997774848)
