### ISSUE TITLE
Deep Feature Selection: Theory and Application to Identify Enhancers and Promoters

### ISSUE THREAD

**Issue by cgreene** [greenelab/deep-review#8]
Paper needs to be read carefully for relevance:
https://dx.doi.org/10.1007/978-3-319-16706-0_20

**Comment by cgreene** [comment]
This one induces sparsity in the first input layer by allowing only one input -> hidden node connection per node. They then introduce constraints on the weight of this mapping to allow regularization. Here, they use elastic net regularization.

This allows learning a single set of features for multi-class problems [cool!]. 

The bio use case is predicting which enhancer-promotor pairs are active. They include features of CpG islands, evolutionary conservation scores, DNA accessibility, histone modifications, and TF binding sites.

They split the dataset for training, validation, and test. It's not entirely clear if they split gene wise, promoter wise, or enhancer wise. I'm going to assume just a random split of promoter-enhancer pair.

Interestingly random forest ended up outperforming the deep feature selection networks on this model when few features are used.

**Comment by akundaje** [comment]
This paper has a lot of problems. I can comment more on it if required. We've actually looked at this a bit and this is a very ad hoc way of performing feature selection. It doesn't perform well. There are much better ways to do this.

**Comment by cgreene** [comment]
@akundaje : Are you willing to share the better ways and/or examples of it? I assume we will want to talk some about feature selection. I know that I'm interested in discussing unsupervised framings & feature construction, so it could also make sense to touch on selection.

**Comment by akundaje** [comment]
@cgreene Yeah a lot of the current state-of-the-art for feature selection/interpretation of deep nets will be covered in our DeepLIFT paper which is also in that category of methods. Like you said, this paper's method does not even outperform Random Forests with the selected features.

**Comment by cgreene** [comment]
Given the performance concerns discussed above, I plan to set this one aside for now. Feel free to re-open if somebody wants to discuss this further.

**Comment by tristancclark** [comment]
@akundaje Unfortunately, I read this thread after taking the time to implement the deep feature selection technique explored in this paper. It has not worked very well at all, I'm interested to know, what are the main problems and why does it not work? It's is a great idea in theory.
