### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by snikumbh** [greenelab/deep-review#807]
Hi, great work with the collaborative effort to write this review!
I just came across the following few typos in the final version.
1. "**perturbastion-basd** methods" in the subsection titled Assigning example-specific importance scores.
2. "SPEID used a CNN to predicte**d** these interactions [...]"
3. "They found that MHCnuggets—the recurrent neural network—was by far the **fastest training** among the top performing methods."

Good luck with the submission.
Thanks and best wishes,
  Sarvesh

**Comment by cgreene** [comment]
Closed with the merging of #808. Thanks!
