### ISSUE TITLE
DeepCare: A Deep Dynamic Memory Model for Predictive Medicine

### ISSUE THREAD

**Issue by agitter** [greenelab/deep-review#82]
http://doi.org/10.1007/978-3-319-31750-2_3

> Personalized predictive medicine necessitates modeling of patient illness and care processes, which inherently have long-term temporal dependencies. Healthcare observations, recorded in electronic medical records, are episodic and irregular in time. We introduce DeepCare, a deep dynamic neural network that reads medical records and predicts future medical outcomes. At the data level, DeepCare models patient health state trajectories with explicit memory of illness. Built on Long Short-Term Memory (LSTM), DeepCare introduces time parameterizations to handle irregular timing by moderating the forgetting and consolidation of illness memory. DeepCare also incorporates medical interventions that change the course of illness and shape future medical risk. Moving up to the health state level, historical and present health states are then aggregated through multiscale temporal pooling, before passing through a neural network that estimates future outcomes. We demonstrate the efficacy of DeepCare for disease progression modeling and readmission prediction in diabetes, a chronic disease with large economic burden. The results show improved modeling and risk prediction accuracy.

Quick thoughts
- Correctly modeling irregular timing and interventions seem quite important in the clinical setting
- Study a diabetes cohort with over 12k patients, which they split into training, validation, and testing sets
- Table 2 describes the performance for predicting a patient's unplanned readmission within 12 months of a randomly selected discharge.  It compares to standard classifiers that use non-temporal features (random forest, SVM) and simpler versions of the DeepCare model.  DeepCare performs much better based on F-score.
- Uses supervised learning, which complements unsupervised and semi-supervised methods for electronic health records (e.g. #25, #63)

**Comment by trangptm** [comment]
Hi Agitter.

I am a co-author of this paper. Thank you very much for your comments.
If you are interested in this problem, we have an extension of DeepCare with more options, more tasks and more data: 
[https://arxiv.org/pdf/1602.00357v1.pdf](url)

**Comment by agitter** [comment]
@trangptm Thanks for sharing.  I didn't realize that the arXiv version was an extension to the published chapter.  We're actively working on the review now and would be happy to have your thoughts on DeepCare and related EHR applications if you would like to participate.

@cgreene Do you think this fits better with "categorize" or "treat"?  I'm leaning toward "categorize".

**Comment by cgreene** [comment]
@agitter : I agree on more categorize than treat, though I can see it mattering there too. We may want to make a passing mention of it in the treat section. I'm wondering if it should be 'develop treatments for' instead of simply 'treat' - because otherwise 'treat' seems like a superset of categorize.
