### ISSUE TITLE
Provisional acceptance, but some minor changes still to be made - quickly!

### ISSUE THREAD

**Issue by cgreene** [greenelab/deep-review#820]
Dear Dr Greene:

On behalf of the Editor, I am pleased to inform you that your Manuscript rsif-2017-0387.R1 entitled "Opportunities and obstacles for deep learning in biology and medicine" has been accepted for publication in J. R. Soc. Interface.

Because the schedule for publication is very tight, it is a condition of publication that you submit the final version of your manuscript within 10 days. If you do not think you will be able to meet this date please let me know immediately. Failure to do so may cause severe delays in the publication of your manuscript.

To submit your final files, log into https://mc.manuscriptcentral.com/jrsi and enter your Author Centre, where you will find your manuscript title listed under "Manuscripts with Decisions."  Under "Actions," click on "Create a Revision."  Your manuscript number has been appended to denote a revision.

You will be unable to change the originally submitted version of the manuscript.  Instead, upload a new version through your Author Centre.

IMPORTANT:  Your original files are available to you when you upload your final version.  Please delete any redundant files before completing the submission process.

When uploading your final files please make sure that you have:

1) A text file of the manuscript (tex, txt, rtf or doc), references, tables (including captions) and figure captions. Do not upload a PDF as your "Main Document".

2) A separate electronic file of each figure (EPS or print-quality PDF preferred (either format should be produced directly from original creation package), or original software format)

3) Included a 100 word media summary of your paper when requested at submission.  Please ensure you have entered a correct email and telephone number in your user account to ensure accurate details are passed to the media.

4) Included the following sections before the reference list: Author Contributions, Acknowledgements, Data Accessibility, Ethics (where appropriate) and a Funding Statement.

5) All supplementary materials accompanying an accepted article will be treated as in their final form. Note that the Royal Society will not edit or typeset supplementary material and it will be hosted as provided. Please ensure that the supplementary material includes the paper details where possible (authors, article title, journal name).

Supplementary files will be published alongside the paper on the journal website and posted on the online figshare repository (https://figshare.com). The heading and legend provided for each supplementary file during the submission process will be used to create the figshare page, so please ensure these are accurate and informative so that your files can be found in searches. Files on figshare will be made available approximately one week before the accompanying article so that the supplementary material can be attributed a unique DOI.

Once again, thank you for submitting your manuscript to J. R. Soc. Interface and I look forward to receiving your final version. If you have any questions at all, please do not hesitate to contact me.

Best wishes,

Tim Holt

* * * * * * * * * * * * *
Dr TJP Holt
Publishing Editor - Journal of the Royal Society Interface

tel     +44 (0) 20 7451 2649
fax     +44 (0) 20 7976 1837
web   http://publishing.royalsociety.org/interface

Referee(s)' Comments to Author:
Referee: 1

Comments to the Author
The reviewer has no further comments.

Referee: 2

Comments to the Author
The authors have done a convincing job in addressing my previous concerns. I am particularly pleased with the new sections on graph structures (PPI networks etc), TF and promoter analysis, and a very convincing new discussion section on the role of evaluation and uncertainty. This has become a very useful and comprehensive review of deep learning in medicine and biology.

The only, presumably unavoidable, shortcoming is still a comparatively incomplete introduction to deep network structures themselves, although Figure 1 and the new glossary is certainly helpful. However, I understand that technical details on network types was not the focus of this review.

Minor point:
The description of the Variational Autoencoder in the glossary is slightly misleading. It is not trained to "learn normally-distributed features". A VAE rather learns a generative but only approximative probabilistic model of the data (which is often build on normal distributions but not necessarily so).

**Comment by cgreene** [comment]
We have a few revisions that I think we should definitely do in the next week so that we can resubmit this by the deadline:

- [ ] Imaging + healthcare section has some terminology issues that need to be fixed. I'll aim to handle this in the next 2-3 days.
- [ ] VAE table entry fix.
- [ ] PR #815 from @AnneCarpenter

**Comment by cgreene** [comment]
I am not as sure what to do with #813. The clarifications there are helpful, but we may want to keep table them for the next iteration of deep-review (see #810) as changes from new contributors post-acceptance to a manuscript is often an issue. If we had gotten a request to revise instead of accept, it would be much easier to take them at this stage.

**Comment by cgreene** [comment]
Not sure who all to tag on this, since most of the things I can fix with a review from @agitter. But if you have other proposed changes that you'd like to see, please get them here ASAP and make sure that they are modest enough in scope that we can handle them within a week including PR review.

**Comment by stephenra** [comment]
@cgreene Congrats! Happy to submit PR for the VAE table entry.

**Comment by cgreene** [comment]
@stephenra great! 😄

**Comment by agitter** [comment]
Congratulations everyone!

I edited @cgreene's comment above to note that we also need to split the Funding Statement sub-section from the Acknowledgements.  I think we can skip the Data Accessibility sub-section for a review article.

I'm following up on #813 in the comments there.

**Comment by alxndrkalinin** [comment]
Is there a thread discussing terminology issues in the imaging section? Since I contributed that I can help addressing these.

**Comment by qiyanjun** [comment]
Is it worth to add the following citations: 

1. Deep EHR: A Survey of Recent Advances in Deep Learning Techniques for Electronic Health Record (EHR) Analysis, https://arxiv.org/abs/1706.03446

2. Jacob Schreiber, Maxwell W. Libbrecht, Jeff Bilmes, William Stafford Noble. "Nucleotide sequence and DNaseI sensitivity are predictive of 3D chromatin architecture" bioRxiv, 2017

- a deep convolutional neural network that predicts Hi-C contacts at 1 kb resolution using nucleotide sequence and DNaseI assay signal as inputs. Specifically, Rambutan identifies locus pairs that engage in high confidence contacts according to Fit-Hi-C, a previously described method for assigning statistical confidence estimates to Hi-C contacts.

3. Scalable and accurate deep learning for electronic health records
https://arxiv.org/abs/1801.07860

4. Generating and designing DNA with deep generative models
Nathan Killoran, Leo J. Lee, Andrew Delong, David Duvenaud, Brendan J. Frey
https://arxiv.org/abs/1712.06148



--

**Comment by agitter** [comment]
@qiyanjun existing authors are welcome to make _small_ changes adding literature that is very closely related to existing sections if they feel there are important manuscripts to add.  We want to be able to review and merge these changes immediately so it is important to keep them small in scope.

Any new pull requests should be submitted by Monday March 5.

cc @alxndrkalinin https://github.com/greenelab/deep-review/pull/824#issuecomment-369697027.

**Comment by agitter** [comment]
@cgreene for the final submission, I can create a doc version of the manuscript similar to what I did for the diff in #798.  We are still getting incorrect metadata from bioRxiv (https://github.com/greenelab/manubot/issues/16), which I can manually fix.

@dhimmel should we merge the preamble changes from https://github.com/greenelab/manubot-rootstock/pull/114 before the next deep review release?

**Comment by dhimmel** [comment]
> should we merge the preamble changes

Yeah will update now

**Comment by agitter** [comment]
[deep-review-63d2468883ea69ad7ad638c39efab0fcbe026298.zip](https://github.com/greenelab/deep-review/files/1785446/deep-review-63d2468883ea69ad7ad638c39efab0fcbe026298.zip)

Here is a `.doc` file version of https://greenelab.github.io/deep-review/v/63d2468883ea69ad7ad638c39efab0fcbe026298/ that I zipped because GitHub doesn't support `.doc` uploads.

I manually fixed some spacing errors introduced during the copy/paste and converted `Cold Spring Harbor Laboratory` -> `bioRxiv` in the references.

**Comment by cgreene** [comment]
Hearing no objections, should I go ahead and resubmit this to the journal? 🤞

**Comment by agitter** [comment]
Go for it @cgreene!

**Comment by qiyanjun** [comment]
Sure. Please! Thanks a million for making this happen. 

(I thought about adding a few more most-recent references and then realized this might influence many more sections. At this point let us submit as what it is.)

Sent from my iPhone
please excuse misspellings & briefness

**Comment by cgreene** [comment]
Manuscript is back to journal!
> rsif-2017-0387.R2

🤞

**Comment by cgreene** [comment]
Official Accept!

> 07-Mar-2018
> 
> Dear Dr Greene:
> 
> I am pleased to inform you that your manuscript entitled "Opportunities and obstacles for deep learning in biology and medicine" has been accepted in its final form for publication in Journal of the Royal Society Interface.
> 
> Our Production Office will be in contact with you in due course.
> 
> Thank you for your contribution and on behalf of the Editor of J. R. Soc. Interface we look forward to your continued contributions to the Journal.
> 
> Best wishes,
> 
> Tim Holt

**Comment by agitter** [comment]
I released the accepted version of deep review as [`v1.0`](https://github.com/greenelab/deep-review/releases/tag/v1.0).
