### ISSUE TITLE
Categorization of Papers

### ISSUE THREAD

**Issue by brettbj** [greenelab/deep-review#87]
I was selecting some papers to read + review and noticed a few trends - 

Phenotyping  (generally EHR based)
Genomic Sequence Based (Primarily regulatory, CNN's on PSSMs etc.)
Image-based methods

Would it be helpful to create labels and categorize the papers? Might lead naturally to review sections? Are there other categories I missed?

**Comment by gwaygenomics** [comment]
What you have plus:

* Genomic platform based inference (Gene expression, methylation, miRNA, etc)

would be the categories I've seen. I am not sure how the article will be structured at the moment, but I think we should be careful to avoid reproducing the content of [similar reviews](https://github.com/greenelab/deep-review/milestone/2 "review papers")

**Comment by agitter** [comment]
The virtual screening papers I started going through are perhaps another category as well (#45 and the references therein).  They could arguably be a type of phenotyping, especially the cellular assays, but are quite different from EHR phenotypes.

I do think it would be helpful to start labeling papers and organizing what we have.

**Comment by cgreene** [comment]
I am pro-organization. Shall we start to discuss? We've done a lot of
reading and it might be a good time to start the part where we use this
common language to start tackling our question. I can create an issue for
this once I get to my hotel, or someone else can start one.

**Comment by agitter** [comment]
Closing this, we have decided how to organize papers.
