### ISSUE TITLE
Learned protein embeddings for machine learning

### ISSUE THREAD

**Issue by nafizh** [greenelab/deep-review#875]
>Motivation: Machine-learning models trained on protein sequences and their measured functions
can infer biological properties of unseen sequences without requiring an understanding of the
underlying physical or biological mechanisms. Such models enable the prediction and discovery
of sequences with optimal properties. Machine-learning models generally require that their inputs
be vectors, and the conversion from a protein sequence to a vector representation affects the model’s
ability to learn. We propose to learn embedded representations of protein sequences that take
advantage of the vast quantity of unmeasured protein sequence data available. These embeddings
are low-dimensional and can greatly simplify downstream modeling.
Results: The predictive power of Gaussian process models trained using embeddings is comparable
to those trained on existing representations, which suggests that embeddings enable accurate
predictions despite having orders of magnitude fewer dimensions. Moreover, embeddings are simpler
to obtain because they do not require alignments, structural data, or selection of informative
amino-acid properties. Visualizing the embedding vectors shows meaningful relationships
between the embedded proteins are captured.

https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/bty178/4951834

**Comment by nafizh** [comment]
Duplicate - closing down

**Comment by agitter** [comment]
#889 is open for discussion about this paper.
