### ISSUE TITLE
Deep Artificial Neural Networks and Neuromorphic Chips for Big Data Analysis: Pharmaceutical and Bioinformatics Applications

### ISSUE THREAD

**Issue by gwaygenomics** [greenelab/deep-review#89]
https://doi.org/10.3390/ijms17081313

**Comment by agitter** [comment]
Skimming the section headings, it looks like they divide papers by network type (e.g. MLP, CNN, RNN) and then give a few examples from pharma (virtual screening) and bioinformatics in each section.  They don't say too much about any individual method.  I didn't ge tot the part about neuromorphic chips.

**Comment by gwaygenomics** [comment]
The paper is tough to get through - the paragraphs are disjointed and there are several sloppy errors (e.g. listing "Deep Auto-Encoder Networks" twice in the reviewed architectures in `2. Deep Artificial Neural Networks in Pharmacology and Bioinformatics`). The paper also talks about hardware more than other reviews - something that is definitely very important, but probably not worth a significant portion of our review.

**Comment by agitter** [comment]
We don't need this for the virtual screening section.  Reopen if we want it for its neuromorphic computing discussion.  @evancofer is this relevant to our hardware section in the Discussion?

**Comment by evancofer** [comment]
@agitter I am not entirely sure, so I will look into it.

**Comment by evancofer** [comment]
Read it, and I have to agree with @gwaygenomics

**Comment by agitter** [comment]
@evancofer Thanks for looking it over, I'll keep the issue closed.
