### ISSUE TITLE
Entangled Conditional Adversarial Autoencoder for de Novo Drug Discovery

### ISSUE THREAD

**Issue by zhebrak** [greenelab/deep-review#920]
> Modern computational approaches and machine learning techniques accelerate the invention of new drugs. Generative models can discover novel molecular structures within hours, while conventional drug discovery pipelines require months of work. In this article, we propose a new generative architecture, entangled conditional adversarial autoencoder, that generates molecular structures based on various properties, such as activity against a specific protein, solubility, or ease of synthesis. We apply the proposed model to generate a novel inhibitor of Janus kinase 3, implicated in rheumatoid arthritis, psoriasis, and vitiligo. The discovered molecule was tested in vitro and showed good activity and selectivity.

http://dx.doi.org/10.1021/acs.molpharmaceut.8b00839

**Comment by agitter** [comment]
Presumably this was closed because it is the same paper as #913.  @zhebrak we welcome authors' comments about their own work, so please feel welcome to start the discussion in #913.
