### ISSUE TITLE
Does deep learning induce a strategic inflection point in how we categorize individuals to maintain or restore health?

### ISSUE THREAD

**Issue by cgreene** [greenelab/deep-review#93]
I'm taking the strategic inflection point language from Andy Grove. For a brief description in his own language, here's a link:
http://www.moline-consulting.com/Reinventando/Pagines/cambioconfuerza.htm

Pulling some language from #88, particularly @gwaygenomics and @agitter to put this together.

This could be between diseases or within diseases. Earlier @agitter highlighted both types. This is my initial categorization but could see arguments for moving some of these around: broad #78 #25 #63; individual: #5 #81 #82 .

So let's discuss: _Does deep learning induce a strategic inflection point in how we categorize individuals to maintain or restore health?_

**Comment by cgreene** [comment]
I am encouraged by progress in this area, but I don't currently see something that completely changes the landscape of how we categorize disease. I like the unsupervised/semisupervised approaches to mining health data (of course, as a co-author on one of them I am probably biased) because phenotyping from health records remains challenging.

**Comment by agitter** [comment]
I proposed the following take on transformative/strategic inflection point:

1. Are the biomedical deep learning methods that exist today transformative in their respective domains?
2. Where in biomedicine could deep learning be transformative regardless of whether that potential has been realized to date?

Even if the answer to 1 is "not many" or "it's too early to tell", there are still exciting things to discuss for 2 based on some of the existing work.  It could also be a way to highlight any work that has been a major leap (maybe #91?).

For 2, it allows us to provide a perspective on what types of biomedical problems and data are well-suited for deep learning.  CNNs on DNA sequence and images have already been covered quite well in existing reviews, so I'd be inclined to mention them but focus more on other applications.

I also think that the suggestion by @gwaygenomics in #88 to include "how we study human disease" is important.  Suppose a new method can do something amazing like perfectly predict chromatin contacts from minimal condition-specific data.  This wouldn't really change how we categorize individuals to maintain or restore health.  But it could certainly influence how we study disease and have an impact on health in the long term.

**Comment by cgreene** [comment]
@agitter : I was going to open the topics on study and treat in series, but would be happy to also see it done in parallel. Do you want to go ahead and open up a parallel issue for study human disease and organize discussion on that issue? I think we have this month to get our thoughts fleshed out via issues. Next month we'll probably commence the drafting.

**Comment by agitter** [comment]
@cgreene Okay, I misunderstood the intention and thought this was a narrowing of scope.  Maybe we should treat the issues serially to try to have a more focused discussion?  Or if you want to proceed in parallel I can start the study disease issue.

**Comment by cgreene** [comment]
Let's go for the parallel approach. If one ends up less active we may
triage or convert from an area of focus into a smaller section.

**Comment by agitter** [comment]
I created #97 for the "study disease" discussion.

If the goal is to start drafting next month, do we want to comment on all of the papers with open issues before then?

**Comment by cgreene** [comment]
Maybe comment and briefly divide into 'study' 'categorize' and 'treat' labels? If there are any papers with open issues that haven't been touched that seem like they might do something totally different than what was previously feasible, we should definitely cover those.

**Comment by cgreene** [comment]
Here's what I'm thinking for breaking out the categorize portion:
* Discovery (static patterns or trajectory) 
* Sharing/privacy
* Standardization/integration
* Storage

I finally have a couple solid blocks of time today, so I'm going to start on the categorize section.

**Comment by agitter** [comment]
I agree that those are important topics in categorizing diseases for precision medicine, but will this substantially expand the scope of the review?  Presenting sharing and privacy issues could be a review on its own.  If there is a way to call out to existing reviews of, e.g. privacy issues, and then discuss how they affect deep learning approaches to categorize disease that would be great.

**Comment by cgreene** [comment]
Well - at the moment it seems like most of the work has been in the first bit. Probably will just point to the others as additional areas to consider. We'll see how it goes today. Going to try to get thoughts into markdown.
