### ISSUE TITLE
Call for Methylation Section

### ISSUE THREAD

**Issue by jlevy44** [greenelab/deep-review#942]
I’ve been reading through the deep review paper and noticed that there is not a Methylation section in this paper. There are a number of issues that have been brought up regarding the inclusion of methylation deep learning papers (#68 #39 #244 #923 #922 #910 #692 ). The only paper I see explicitly mentioned in the paper for deep learning exclusively for methylation data types is DeepCpG (I’ve read the referenced multimodal approaches). However, it seems like there are quite a few papers that demonstrate significant strides in Deep Learning and methylation, most of which are enumerated below:

- Predicting triglyceride concentrations https://bmcproc.biomedcentral.com/articles/10.1186/s12919-018-0121-1, referenced in https://bmcgenet.biomedcentral.com/articles/10.1186/s12863-018-0646-3
- Stacked Restricted Binary Boltzmann Machines to uncover deep methylation features - https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=7484730&tag=1 https://arxiv.org/abs/1808.01359
- Deep Signal - https://www.biorxiv.org/content/early/2018/08/06/385849
- Using a convolutional neural network to classify different types of cancer - https://arxiv.org/abs/1807.09617 
- DAPL for imputation- https://www.biorxiv.org/content/early/2018/09/03/406066 
- Predicting DNAm via Deep Belief Networks - https://ieeexplore.ieee.org/abstract/document/8325078 
- Deep Learning for Gene Promoter Methylation Inference - https://www.biorxiv.org/content/early/2018/10/09/438218 
- MGMT Methylation Status Prediction - https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5603430/ 
- Variational Autoencoders to extract biologically meaningful information from learned latent space
        - http://www.scitepress.org/DigitalLibrary/Link.aspx?doi=10.5220/0006636401400145
        - https://www.biorxiv.org/content/early/2018/11/07/433763 
- Inferring methylation status, DeepCpG

I believe that the inclusion of methylation in the deep learning paper has been limited, and propose that we include a Methylation section of the paper under the “Deep learning to study the fundamental biological processes underlying human disease section”.

Brock Christensen @Christensen-Lab, Alexander Titus @AlexanderTitus, and I have been working together to draft a Methylation section for the deep review paper, which we are revising internally, and would be happy to submit a pull request soon. The three of us would also like to be included as authors in the paper.

**Comment by evancofer** [comment]
We'd love to see your contributions. From what you say, the addition of such a subsection seems apropos.

For the sake of efficiency and this project's focus on open/collaborative writing, I recommend that you submit a public pull requests before you get too far along. This will help publicly document all your contributions, ensure that your additions pass automated checks, and make it easier for others to make comments on your proposed additions (and thereby ensure that you're on the right track in terms of content, formatting, etc).

Authorship isn't decided immediately, since authors are defined as anyone who has met ICMJE authorship standards (defined [here](http://www.icmje.org/recommendations/browse/roles-and-responsibilities/defining-the-role-of-authors-and-contributors.html)) at the time of submission. The *"at the time of submission"* part is critical, e.g. some contributors to the first release were not listed as authors because they did not indicate their approval of the final manuscript. @cgreene may have more to say about this.

**Comment by cgreene** [comment]
@evancofer's summary seems on point. Things that we required were participation. This means that if you submit a fully formed PR but it only comes from one account, that provides contribution credit to that person but not the others - who may have contributed behind the scenes but did not in a public, attributable way.

To be an author requires meeting all of the criteria, and this does require approval of the manuscript to be submitted. We attempted to obtain this from everyone, but there were authors who did not respond despite efforts to reach out to them, so we included them in only the acknowledgements.

**Comment by Christensen-Lab** [comment]
Great, thanks for the quick response. We have already begun drafting content, it appears that the "time of submission" will be June 2019 correct? Thanks

**Comment by evancofer** [comment]
Yes, June 2019 is correct.

**Comment by jlevy44** [comment]
Thanks for your quick responses. Brock, Alexander and I will discuss our next steps as we continue to draft the methylation section.

**Comment by evancofer** [comment]
Great. I'm excited to see what you all have been working on. It sounds like it would make a great addition!

**Comment by evancofer** [comment]
Any updates on this?

**Comment by jlevy44** [comment]
Hey there. No updates yet. I'll touch base with @AlexanderTitus and @Christensen-Lab so we can start to make more progress.

**Comment by jlevy44** [comment]
I believe we're shooting to have something preliminary by mid-February to early-March.

**Comment by jlevy44** [comment]
Just providing another update. We’ll be releasing our section through three separate PRs. I’ll PR some motivational material for why deep learning and methylation, and then @Christensen-Lab and @AlexanderTitus will review and edit text that I wrote surrounding methylation inference, predictions, and latent space, and each will submit a PR for their relevant methylation subsection. Hoping to release the intro soon to have something down and in the process of merging.

**Comment by jlevy44** [comment]
Hey everyone, just giving an update. We're just waiting on internal edits before we send the entire section out (may update with a few new papers).

Do you have a deadline of when you'd like for us to have this section in by?

**Comment by evancofer** [comment]
I don't know if there is a deadline for this section per se. The sooner you can get the internal edits in a PR, the sooner you can get some feedback on it. Based on the last PR, feedback may be a little slow, so it is better to post things sooner than later.

**Comment by jlevy44** [comment]
Internal review is progressing, should have that PR soon...

**Comment by jlevy44** [comment]
What's the best way to multiple PR one section? Internal reviews are complete. Just adding citations. We'd like to make 2-3 PRs, one for each author.

**Comment by evancofer** [comment]
I am not sure I understand the question, could you clarify? Either way, I am glad to know it's getting closer to PR stage.

**Comment by agitter** [comment]
@evancofer the question is how to coordinate multiple related PRs so that each contributor gets credit for their text and there aren't complex merge conflicts.

@jlevy44 as long as the PRs don't edit the same existing text, it should be okay to submit them all at once as separate PRs.  The last one submitted can reference the PR numbers of the others to help coordinate review.  Does that sound okay @evancofer?

Note that the last methylation section PR struggled to find a qualified reviewer, so that may be a problem here as well.  We haven't done it before, but maybe you could recruit an external reviewer (i.e. not an existing author) and we could acknowledge them?

**Comment by jlevy44** [comment]
Our team has begun the PR process. You should expect 2 more PRs this week.

Here are the order of the PR sections that our group will be submitting:
1. Introductions - @Christensen-Lab @Christensen-Lab-Dartmouth
2. Inference, Imputation, and Prediction - @jlevy44
3. Latent Space Construction and Conclusions - @AlexanderTitus

**Comment by evancofer** [comment]
I agree with @agitter that finding qualified reviewers is the real issue here. If they have the time, either @michaelmhoffman or @lanagarmire are probably good choices, who IIRC were involved with the first iteration of the deep review

**Comment by jlevy44** [comment]
Great. Is there anything I can do to help move things forward at this stage?

**Comment by michaelmhoffman** [comment]
Thanks for thinking of me, but given my commitments I need to prioritize contributions that will lead to a new paper.

**Comment by lanagarmire** [comment]
Happy to help and move the manuscript to move forward as a co-author.

Lana Garmire, PhD
Associate Professor (with tenure)
Department of Computational Medicine and Bioinformatics
School of Medicine
University of Michigan
groupwebsite: garmiregroup.org

**Comment by evancofer** [comment]
@jlevy44 I think our efforts right now should focus on continuing to update existing sections, and summarizing and discussing new work using the GitHub issues.

@michaelmhoffman No problem. Thank you for filling us in on the situation!

@lanagarmire We'd love to have your contribution. If you're up to reviewing some of the methylation content, I think there are three PRs open right now that cover the methylation sections:
- section introduction: #956 
- inference, imputation, prediction: #954 
- latent space construction #955
This is definitely a lot to review, so I am aiming to have several people give this a look over before it's merged. Ideally, we'll have those with background in methylation review content, and others can review formatting etc.

@cgreene Is there a previous PR that stands out as the "ideal" example of how we should do these PR-based reviews? I think it might be useful for onboarding reviewers, and could be worth mentioning in `CONTRIBUTING.md`.

**Comment by cgreene** [comment]
@evancofer : this was a new subsection, and may be a good example to work from:

https://github.com/greenelab/deep-review/pull/629

**Comment by jlevy44** [comment]
@lanagarmire We'll be more than happy to have you review our sections.

**Comment by jlevy44** [comment]
Thank you for the help!

**Comment by AlexanderTitus** [comment]
If there is anything we can do to facilitate review, please let us know. 

We would love to have this section included in the next iteration of the review released, as it adds to the completeness of the review.

**Comment by jlevy44** [comment]
@evancofer @cgreene What would you recommend as the next steps for the completion of this review? In particular, what might be some action steps for @lanagarmire to review our content?

Thanks!

**Comment by lanagarmire** [comment]
I will have a block of time early next week. Is the draft ready for QC/check?

**Comment by evancofer** [comment]
@lanagarmire I think their current draft is ready for QC. @jlevy44  any last minute changes?

**Comment by jlevy44** [comment]
@lanagarmire @evancofer I think we're all good to go. 
One of our PRs did not pass through Travis, but should be okay content-wise.

Thanks!

**Comment by cgreene** [comment]
Do you know why Travis failed? Might be good to clean that up first too.
Can't merge until it passes, even if PR approved.

**Comment by agitter** [comment]
@cgreene it looks like a space vs. tab failure in the tags file https://github.com/greenelab/deep-review/pull/956#discussion_r292874898

**Comment by jlevy44** [comment]
I thought that there was a mechanism in place to automatically reread the tsv with a new delimiter. If you check the Travis output for my PR, the same error may be embedded?

@brockclarke

**Comment by jlevy44** [comment]
@lanagarmire looking forward to your review of our material. Hopefully we can finish this review before the submission of the manuscript. Please let me know what I can do to help move things forward.

**Comment by lanagarmire** [comment]
Does this qualify me as a co-author? Forgot to ask...need to prioritize my
time wisely, obviously.  Thanks.

**Comment by cgreene** [comment]
@lanagarmire It will depend on the extent to which your review meets the ICMJE guidelines:
https://github.com/greenelab/deep-review/blob/master/CONTRIBUTING.md#authorship

The two that are most in question here (the others are approval/agreement) are:

> Substantial contributions to the conception or design of the work; or the acquisition, analysis, or interpretation of data for the work; AND

> Drafting the work or revising it critically for important intellectual content; AND

If you make specific suggestions to the text that revise it for critically important content (now far more trackable via github's suggest changes feature, which I would strongly encourage you to use so that your suggestions can be tracked) that get incorporated, and make contributions to the design of the sections (i.e., if you identify substantial changes that improve clarity or identify missing areas/literature that should be covered), that would qualify.

On the other hand, if the changes are primarily copyediting, etc then that wouldn't qualify.

If you are uncomfortable with this, then I wouldn't encourage you to do it and we can find another path. If this is something you are comfortable with, we would like to benefit from your expertise!

**Comment by cgreene** [comment]
@jlevy44 : Can someone accept @agitter's change on https://github.com/greenelab/deep-review/pull/956

The permissions on the fork are set such that I don't have permission to commit to @brockclarke's branch there.

**Comment by lanagarmire** [comment]
I already contrbuted to critical suggestions before the writing. That is
why I was asked to QC.

But if you don't think that matter then i will pass this one.

**Comment by cgreene** [comment]
@lanagarmire : Each contribution matters, but I don't think there would be anyone who could guarantee that ICMJE guidelines for authorship would be met before the review is done. If you feel you need to pass, I totally understand.

**Comment by lanagarmire** [comment]
Good luck to your review!!!

**Comment by jlevy44** [comment]
@brockclarke Can you accept @agitter ‘s change on #956 ? 

@lanagamire Thanks!

@cgreene @agitter @evancofer 
Is there anyone else you could suggest as a reviewer? I can also ask around.

**Comment by jlevy44** [comment]
Hey @cgreene , can you provide us an update with the status of the review of these 3 PRs? Thanks!

Looking forward to moving our contributions to their final state. If we could also add this manuscript to the review before submission that would be great: https://www.biorxiv.org/content/10.1101/692665v1

**Comment by cgreene** [comment]
Getting this moving again is one of my three main goals of this week! 🤞

**Comment by jlevy44** [comment]
Wonderful. Thanks @cgreene !

**Comment by lanagarmire** [comment]
Please take me off this thread.thx

**Comment by cgreene** [comment]
@lanagarmire : your github preferences have you subscribed - nobody else can remove you, but these instructions might be helpful:
https://help.github.com/en/articles/subscribing-to-and-unsubscribing-from-notifications

**Comment by jlevy44** [comment]
I think we can wrap this up and close this issue once #959 is resolved. Thanks!

**Comment by agitter** [comment]
Closed by #954 #955 #956

**Comment by jlevy44** [comment]
Any interest in having us update this section?

**Comment by agitter** [comment]
This methylation section is one of the most recently written parts of the review, so I don't see a major need to update it.  That said, the initial version was added over a year ago, so we would welcome updates if you have them.

It may take us a while to review any updates.

**Comment by brockclarke** [comment]
Is there a plan to publish an updated version of this review?
There are of course publications in the past year that we could include, but we would not want to delay publication plans, or go to the work if there aren’t plans in place

**Comment by agitter** [comment]
There are still vague plans to publish an update at some point.  However, given the current activity level of contributors who are helping write content and review pull requests, I don't think we can set a timeline for the next submission.
