### ISSUE TITLE
Class imbalance in Deepr 

### ISSUE THREAD

**Issue by NandhiniSubramanyan** [greenelab/deep-review#950]
You have mentioned in Deepr paper that you had only 2% unplannned readmission data. But you haven't mentioned anything about how you managed the class imbalance. Could you please share how you solved the problem?

**Comment by stephenra** [comment]
@NandhiniSubramanyan Are you referring to the paper ["Deepr: A Convolutional Net for Medical Records"](https://arxiv.org/abs/1607.07519)? If so, please note that this repository and its issues are for a review paper of applications of deep learning in biology and medicine. If you have questions about a particular paper, I would suggest reaching out to the authors of the paper directly.
