### ISSUE TITLE
Reference Error in Royal Society Paper

### ISSUE THREAD

**Issue by smthomas-sci** [greenelab/deep-review#975]
I found a reference error in Section 5.3 - reference 448 should point to (I think)  https://aaas.confex.com/aaas/2017/webprogram/Paper19142.html but instead points to 
https://arxiv.org/abs/1312.6184 (not even relevant) - same author, wrong reference. 

https://greenelab.github.io/deep-review/#interpretation

**Comment by agitter** [comment]
Good catch @smthomas-sci.  I'll look into this more before making a pull request, but this does appear to be an error.  It may originate in #368.  Tag `Caruana2015_intelligible` was introduced, which refers to the relevant reference https://dl.acm.org/citation.cfm?id=2788613.  However, this intepretation paragraph text cites `[@tag:Caruana2014_need]`.

The reference number is currently 495 in version https://greenelab.github.io/deep-review/v/360c9a496dacc5833a25c1e083bc3f9a892272d6/
